In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/processed/dataset_long_pruned.csv')
print(df.shape)
df.head()

(27300, 17)

,iv_roll_mean_10,iv_roll_mean_5,iv_neighbor_mean,wide_iv_neighbor_mean,strike,iv_neighbor_+1,iv_neighbor_-1,iv_neighbor_+2,iv_neighbor_-2,dist_from_atm_pct,moneyness,log_moneyness,iv,contract,option_type,date,datetime
0,NaN,NaN,0.12330,0.11741,25200,0.12330,NaN,0.11741,NaN,0.034914,0.965086,-0.035538,0.12662,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:15:00
1,NaN,NaN,NaN,NaN,25200,NaN,NaN,NaN,NaN,0.036012,0.963988,-0.036676,0.08632,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:20:00
2,NaN,0.106470,NaN,0.09514,25200,NaN,NaN,0.09514,NaN,0.035936,0.964064,-0.036598,0.09147,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:25:00
3,0.101470,0.101470,0.10842,0.11150,25200,0.10842,NaN,0.11150,NaN,0.035553,0.964447,-0.036200,0.10860,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:30:00
4,0.103252,0.103252,0.10538,0.12459,25200,0.10538,NaN,0.12459,NaN,0.035661,0.964339,-0.036313,0.10462,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:35:00

In [10]:
contract_strike = (
    df['contract']
    .str.extract(r'(\d{5})(?=CE$|PE$)')[0]
    .astype(int)
)

(contract_strike != df['strike']).sum()

np.int64(0)

In [9]:
df[['contract','strike']].head()

              contract  strike
0  NIFTY27JAN2625200CE   25200
1  NIFTY27JAN2625200CE   25200
2  NIFTY27JAN2625200CE   25200
3  NIFTY27JAN2625200CE   25200
4  NIFTY27JAN2625200CE   25200