In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv('../data/processed/dataset_long.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
df.head()

,datetime,underlying_price,contract,iv,option_type,strike,hour,minute,day_of_week,date,session_progress,days_to_expiry,moneyness,log_moneyness,dist_from_atm,dist_from_atm_pct,is_ce,strike_rank,iv_neighbor_-2,iv_neighbor_-1,iv_neighbor_+1,iv_neighbor_+2,iv_neighbor_mean,wide_iv_neighbor_mean,iv_lag_1,iv_roll_mean_5,iv_roll_std_5,iv_roll_mean_10,mean_ce_iv,mean_pe_iv
0,2026-01-07 09:15:00,26111.65,NIFTY27JAN2625200CE,0.12662,CE,25200,9,15,2,2026-01-07,4860.0,20.2569,0.965086,-0.035538,911.65,0.034914,1,0.0,NaN,NaN,0.12330,0.11741,0.12330,0.11741,NaN,NaN,NaN,NaN,0.102447,0.102447
1,2026-01-07 09:20:00,26141.40,NIFTY27JAN2625200CE,0.08632,CE,25200,9,20,2,2026-01-07,4865.0,20.2535,0.963988,-0.036676,941.40,0.036012,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.12662,NaN,NaN,NaN,0.098723,0.098723
2,2026-01-07 09:25:00,26139.35,NIFTY27JAN2625200CE,0.09147,CE,25200,9,25,2,2026-01-07,4870.0,20.2500,0.964064,-0.036598,939.35,0.035936,1,0.0,NaN,NaN,NaN,0.09514,NaN,0.09514,0.08632,0.106470,0.028496,NaN,0.091074,0.091074
3,2026-01-07 09:30:00,26128.95,NIFTY27JAN2625200CE,0.10860,CE,25200,9,30,2,2026-01-07,4875.0,20.2465,0.964447,-0.036200,928.95,0.035553,1,0.0,NaN,NaN,0.10842,0.11150,0.10842,0.11150,0.09147,0.101470,0.021932,0.101470,0.103252,0.103252
4,2026-01-07 09:35:00,26131.90,NIFTY27JAN2625200CE,0.10462,CE,25200,9,35,2,2026-01-07,4880.0,20.2431,0.964339,-0.036313,931.90,0.035661,1,0.0,NaN,NaN,0.10538,0.12459,0.10538,0.12459,0.10860,0.103252,0.018259,0.103252,0.104097,0.104097

In [4]:
df.columns

Index(['datetime', 'underlying_price', 'contract', 'iv', 'option_type',
       'strike', 'hour', 'minute', 'day_of_week', 'date', 'session_progress',
       'days_to_expiry', 'moneyness', 'log_moneyness', 'dist_from_atm',
       'dist_from_atm_pct', 'is_ce', 'strike_rank', 'iv_neighbor_-2',
       'iv_neighbor_-1', 'iv_neighbor_+1', 'iv_neighbor_+2',
       'iv_neighbor_mean', 'wide_iv_neighbor_mean', 'iv_lag_1',
       'iv_roll_mean_5', 'iv_roll_std_5', 'iv_roll_mean_10', 'mean_ce_iv',
       'mean_pe_iv'],
      dtype='str')

In [20]:
dates = sorted(df['datetime'].dt.date.unique())

folds = [
    {'name': 'Fold 1', 'train_dates': dates[:9],  'val_dates': dates[9:11]},
    {'name': 'Fold 2', 'train_dates': dates[:10], 'val_dates': dates[10:12]},
]

In [7]:
def make_holdout(val_df,random_state=2):
    np.random.seed(42)

    available_rows = val_df[val_df['iv'].notna()].index

    hidden_rows = np.random.choice(available_rows,size=int(0.2*len(available_rows)),replace=False)

    ground_truth = val_df.loc[hidden_rows,'iv'].values

    val_masked = val_df.copy()

    val_masked.loc[hidden_rows,'iv'] = np.nan

    return val_masked,hidden_rows,ground_truth

In [8]:
# evaluation functions for ml models
def eval_pred(actual,predicted):
    valid = ~np.isnan(predicted)

    mse = mean_squared_error(actual[valid],predicted[valid])
    coverage = valid.mean()

    print(f"MSE: {mse:6f}")
    print(f"Coverage: {coverage:6f}")

    return mse,coverage

In [9]:
import xgboost
import lightgbm
import catboost

### Model 1: XGBoost will all features

In [21]:
from xgboost import XGBRegressor

fold_mses, fold_coverages, feature_importances = [],[],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df[df['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df[df['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)
    feature_importances.append(xgb_model.feature_importances_)

print(f"xgb_mse: {np.mean(fold_mses):6f}")
print(f"xgb_coverage: {np.mean(fold_coverages):6f}")
print(f"feature importances: {feature_importances}")

MSE: 0.000060
Coverage: 1.000000
MSE: 0.000047
Coverage: 1.000000
xgb_mse: 0.000054
xgb_coverage: 1.000000
feature importances: [array([0.00363282, 0.00907561, 0.00155192, 0.00223305, 0.00444412,
       0.00367086, 0.00336628, 0.00785213, 0.00631918, 0.00849222,
       0.00983764, 0.        , 0.00690801, 0.0082335 , 0.00724757,
       0.01690204, 0.01307639, 0.5044574 , 0.05791805, 0.00531302,
       0.2592039 , 0.00362226, 0.0293275 , 0.01106107, 0.01625342],
      dtype=float32), array([0.00247129, 0.00621403, 0.00108871, 0.00110867, 0.00310131,
       0.00215398, 0.00219415, 0.02390117, 0.00368832, 0.0064261 ,
       0.00643909, 0.0005458 , 0.00393209, 0.00472965, 0.00666619,
       0.0132345 , 0.00542649, 0.26722205, 0.03958256, 0.00331858,
       0.49992165, 0.00180436, 0.07908553, 0.00519456, 0.01054917],
      dtype=float32)]

In [22]:
avg_importance = np.mean(feature_importances,axis=0)

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': avg_importance
})

importance_df = importance_df.sort_values(by='importance',ascending=False)

importance_df

                  feature  importance
17       iv_neighbor_mean    0.385840
20         iv_roll_mean_5    0.379563
22        iv_roll_mean_10    0.054207
18  wide_iv_neighbor_mean    0.048750
7               moneyness    0.015877
15         iv_neighbor_+1    0.015068
24             mean_pe_iv    0.013401
16         iv_neighbor_+2    0.009251
10      dist_from_atm_pct    0.008138
23             mean_ce_iv    0.008128
1                  strike    0.007645
9           dist_from_atm    0.007459
14         iv_neighbor_-1    0.006957
13         iv_neighbor_-2    0.006482
12            strike_rank    0.005420
8           log_moneyness    0.005004
19               iv_lag_1    0.004316
4             day_of_week    0.003773
0        underlying_price    0.003052
5        session_progress    0.002912
6          days_to_expiry    0.002780
21          iv_roll_std_5    0.002713
3                  minute    0.001671
2                    hour    0.001320
11                  is_ce    0.000273

In [24]:
selected_features = importance_df[importance_df['importance']>=0.005]['feature'].tolist()

selected_features

['iv_neighbor_mean',
 'iv_roll_mean_5',
 'iv_roll_mean_10',
 'wide_iv_neighbor_mean',
 'moneyness',
 'iv_neighbor_+1',
 'mean_pe_iv',
 'iv_neighbor_+2',
 'dist_from_atm_pct',
 'mean_ce_iv',
 'strike',
 'dist_from_atm',
 'iv_neighbor_-1',
 'iv_neighbor_-2',
 'strike_rank',
 'log_moneyness']

In [25]:
df_pruned = df[selected_features+['iv','contract','option_type','date','datetime']].copy()
print(df_pruned.shape)
df_pruned.head()

(27300, 21)

,iv_neighbor_mean,iv_roll_mean_5,iv_roll_mean_10,wide_iv_neighbor_mean,moneyness,iv_neighbor_+1,mean_pe_iv,iv_neighbor_+2,dist_from_atm_pct,mean_ce_iv,strike,dist_from_atm,iv_neighbor_-1,iv_neighbor_-2,strike_rank,log_moneyness,iv,contract,option_type,date,datetime
0,0.12330,NaN,NaN,0.11741,0.965086,0.12330,0.102447,0.11741,0.034914,0.102447,25200,911.65,NaN,NaN,0.0,-0.035538,0.12662,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:15:00
1,NaN,NaN,NaN,NaN,0.963988,NaN,0.098723,NaN,0.036012,0.098723,25200,941.40,NaN,NaN,0.0,-0.036676,0.08632,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:20:00
2,NaN,0.106470,NaN,0.09514,0.964064,NaN,0.091074,0.09514,0.035936,0.091074,25200,939.35,NaN,NaN,0.0,-0.036598,0.09147,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:25:00
3,0.10842,0.101470,0.101470,0.11150,0.964447,0.10842,0.103252,0.11150,0.035553,0.103252,25200,928.95,NaN,NaN,0.0,-0.036200,0.10860,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:30:00
4,0.10538,0.103252,0.103252,0.12459,0.964339,0.10538,0.104097,0.12459,0.035661,0.104097,25200,931.90,NaN,NaN,0.0,-0.036313,0.10462,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:35:00

In [26]:
df_pruned.to_csv('../data/processed/dataset_long_pruned.csv',index=False)

### Model 2: XGBoost with pruned features

In [27]:
fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)

print(f"xgbp_mse: {np.mean(fold_mses):6f}")
print(f"xgbp_coverage: {np.mean(fold_coverages):6f}")

MSE: 0.000044
Coverage: 1.000000
MSE: 0.000035
Coverage: 1.000000
xgbp_mse: 0.000040
xgbp_coverage: 1.000000

### Model 3: LightGBM

In [28]:
from lightgbm import LGBMRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    lgbm_model = LGBMRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    lgbm_model.fit(X_train,y_train)
    lgbm_pred = lgbm_model.predict(X_val)

    lgbm_mse, lgbm_coverage = eval_pred(ground_truth,lgbm_pred)

    fold_mses.append(lgbm_mse)
    fold_coverages.append(lgbm_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"lgbm_mse: {np.mean(fold_mses):6f}")
print(f"lgbm_coverage: {np.mean(fold_coverages):6f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008621 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3597
[LightGBM] [Info] Number of data points in the train set: 15192, number of used features: 16
[LightGBM] [Info] Start training from score 0.108086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
MSE: 0.000046
Coverage: 1.000000
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000582 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3599
[LightGBM] [Info] Number of data points in the train set: 16882, number of used features: 16
[LightGBM] [Info] Start training from score 0.111642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Model 4: CatBoost

In [29]:
from catboost import CatBoostRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    cb_model = CatBoostRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        random_state= 2,
    )

    cb_model.fit(X_train,y_train)
    cb_pred = cb_model.predict(X_val)

    cb_mse, cb_coverage = eval_pred(ground_truth,cb_pred)

    fold_mses.append(cb_mse)
    fold_coverages.append(cb_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"cb_mse: {np.mean(fold_mses):6f}")
print(f"cb_coverage: {np.mean(fold_coverages):6f}")

0:	learn: 0.0129226	total: 10ms	remaining: 4.99s
1:	learn: 0.0124073	total: 15.9ms	remaining: 3.96s
2:	learn: 0.0119148	total: 23ms	remaining: 3.81s
3:	learn: 0.0114542	total: 27.1ms	remaining: 3.36s
4:	learn: 0.0110246	total: 33.3ms	remaining: 3.29s
5:	learn: 0.0106173	total: 37.6ms	remaining: 3.1s
6:	learn: 0.0102425	total: 42.4ms	remaining: 2.98s
7:	learn: 0.0098614	total: 46.2ms	remaining: 2.84s
8:	learn: 0.0095130	total: 50.2ms	remaining: 2.74s
9:	learn: 0.0091722	total: 54.3ms	remaining: 2.66s
10:	learn: 0.0088422	total: 58.6ms	remaining: 2.61s
11:	learn: 0.0085460	total: 62.8ms	remaining: 2.56s
12:	learn: 0.0082627	total: 66.5ms	remaining: 2.49s
13:	learn: 0.0079828	total: 70ms	remaining: 2.43s
14:	learn: 0.0077328	total: 73.7ms	remaining: 2.38s
15:	learn: 0.0074874	total: 76.6ms	remaining: 2.32s
16:	learn: 0.0072592	total: 79.3ms	remaining: 2.25s
17:	learn: 0.0070322	total: 83.6ms	remaining: 2.24s
18:	learn: 0.0068237	total: 86.7ms	remaining: 2.19s
19:	learn: 0.0066303	total: 89.7ms	remaining: 2.15s
20:	learn: 0.0064401	total: 93.3ms	remaining: 2.13s
21:	learn: 0.0062636	total: 96.8ms	remaining: 2.1s
22:	learn: 0.0061053	total: 99.2ms	remaining: 2.06s
23:	learn: 0.0059428	total: 102ms	remaining: 2.02s
24:	learn: 0.0057887	total: 105ms	remaining: 2s
25:	learn: 0.0056452	total: 108ms	remaining: 1.96s
26:	learn: 0.0055109	total: 111ms	remaining: 1.94s
27:	learn: 0.0053850	total: 113ms	remaining: 1.91s
28:	learn: 0.0052629	total: 116ms	remaining: 1.89s
29:	learn: 0.0051532	total: 119ms	remaining: 1.86s
30:	learn: 0.0050398	total: 121ms	remaining: 1.84s
31:	learn: 0.0049365	total: 124ms	remaining: 1.82s
32:	learn: 0.0048437	total: 127ms	remaining: 1.8s
33:	learn: 0.0047470	total: 130ms	remaining: 1.79s
34:	learn: 0.0046610	total: 133ms	remaining: 1.77s
35:	learn: 0.0045836	total: 137ms	remaining: 1.76s
36:	learn: 0.0045111	total: 140ms	remaining: 1.75s
37:	learn: 0.0044364	total: 144ms	remaining: 1.75s
38:	learn: 0.0043635	total: 147ms	remaining: 1.74s
39:	learn: 0.0042976	total: 151ms	remaining: 1.74s
40:	learn: 0.0042351	total: 154ms	remaining: 1.72s
41:	learn: 0.0041791	total: 157ms	remaining: 1.71s
42:	learn: 0.0041257	total: 160ms	remaining: 1.7s
43:	learn: 0.0040745	total: 163ms	remaining: 1.69s
44:	learn: 0.0040242	total: 165ms	remaining: 1.67s
45:	learn: 0.0039801	total: 168ms	remaining: 1.66s
46:	learn: 0.0039362	total: 172ms	remaining: 1.65s
47:	learn: 0.0038972	total: 174ms	remaining: 1.64s
48:	learn: 0.0038600	total: 177ms	remaining: 1.63s
49:	learn: 0.0038248	total: 180ms	remaining: 1.62s
50:	learn: 0.0037908	total: 184ms	remaining: 1.62s
51:	learn: 0.0037537	total: 187ms	remaining: 1.61s
52:	learn: 0.0037237	total: 189ms	remaining: 1.59s
53:	learn: 0.0036935	total: 193ms	remaining: 1.59s
54:	learn: 0.0036671	total: 195ms	remaining: 1.58s
55:	learn: 0.0036398	total: 198ms	remaining: 1.57s
56:	learn: 0.0036164	total: 200ms	remaining: 1.56s
57:	learn: 0.0035874	total: 203ms	remaining: 1.55s
58:	learn: 0.0035599	total: 206ms	remaining: 1.54s
59:	learn: 0.0035340	total: 209ms	remaining: 1.53s
60:	learn: 0.0035132	total: 211ms	remaining: 1.52s
61:	learn: 0.0034910	total: 214ms	remaining: 1.51s
62:	learn: 0.0034718	total: 216ms	remaining: 1.5s
63:	learn: 0.0034549	total: 220ms	remaining: 1.5s
64:	learn: 0.0034362	total: 224ms	remaining: 1.5s
65:	learn: 0.0034185	total: 228ms	remaining: 1.5s
66:	learn: 0.0033993	total: 233ms	remaining: 1.51s
67:	learn: 0.0033863	total: 236ms	remaining: 1.5s
68:	learn: 0.0033719	total: 240ms	remaining: 1.5s
69:	learn: 0.0033560	total: 244ms	remaining: 1.5s
70:	learn: 0.0033413	total: 248ms	remaining: 1.5s
71:	learn: 0.0033253	total: 251ms	remaining: 1.49s
72:	learn: 0.0033116	total: 254ms	remaining: 1.48s
73:	learn: 0.0032990	total: 256ms	remaining: 1.48s
74:	learn: 0.0032826	total: 259ms	remaining: 1.47s
75:	learn: 0.0032692	total: 261ms	remaining: 1.46s
76:	learn: 0.0032583	total: 264ms	remaining: 1.45s
77:	learn: 0.0032470	total: 267ms	remaining: 1.45s
78:	learn: 0.0032325	total: 270ms	remaining: 1.44s
79:	learn: 0.0032180	total: 273ms	remaining: 1.43s
80:	learn: 0.0032069	total: 276ms	remaining: 1.43s
81:	learn: 0.0031971	total: 278ms	remaining: 1.42s
82:	learn: 0.0031841	total: 281ms	remaining: 1.41s
83:	learn: 0.0031757	total: 284ms	remaining: 1.41s
84:	learn: 0.0031658	total: 286ms	remaining: 1.4s
85:	learn: 0.0031572	total: 289ms	remaining: 1.39s
86:	learn: 0.0031472	total: 292ms	remaining: 1.39s
87:	learn: 0.0031390	total: 295ms	remaining: 1.38s
88:	learn: 0.0031298	total: 299ms	remaining: 1.38s
89:	learn: 0.0031205	total: 302ms	remaining: 1.37s
90:	learn: 0.0031131	total: 305ms	remaining: 1.37s
91:	learn: 0.0031056	total: 307ms	remaining: 1.36s
92:	learn: 0.0030976	total: 311ms	remaining: 1.36s
93:	learn: 0.0030902	total: 316ms	remaining: 1.36s
94:	learn: 0.0030828	total: 319ms	remaining: 1.36s
95:	learn: 0.0030751	total: 323ms	remaining: 1.36s
96:	learn: 0.0030695	total: 328ms	remaining: 1.36s
97:	learn: 0.0030620	total: 333ms	remaining: 1.36s
98:	learn: 0.0030548	total: 336ms	remaining: 1.36s
99:	learn: 0.0030482	total: 339ms	remaining: 1.35s
100:	learn: 0.0030420	total: 342ms	remaining: 1.35s
101:	learn: 0.0030341	total: 346ms	remaining: 1.35s
102:	learn: 0.0030287	total: 349ms	remaining: 1.34s
103:	learn: 0.0030243	total: 351ms	remaining: 1.34s
104:	learn: 0.0030171	total: 355ms	remaining: 1.33s
105:	learn: 0.0030128	total: 357ms	remaining: 1.33s
106:	learn: 0.0030067	total: 360ms	remaining: 1.32s
107:	learn: 0.0029994	total: 363ms	remaining: 1.32s
108:	learn: 0.0029907	total: 366ms	remaining: 1.31s
109:	learn: 0.0029838	total: 369ms	remaining: 1.31s
110:	learn: 0.0029769	total: 372ms	remaining: 1.3s
111:	learn: 0.0029700	total: 375ms	remaining: 1.3s
112:	learn: 0.0029619	total: 378ms	remaining: 1.29s
113:	learn: 0.0029565	total: 382ms	remaining: 1.29s
114:	learn: 0.0029516	total: 385ms	remaining: 1.29s
115:	learn: 0.0029435	total: 389ms	remaining: 1.29s
116:	learn: 0.0029380	total: 393ms	remaining: 1.28s
117:	learn: 0.0029312	total: 397ms	remaining: 1.28s
118:	learn: 0.0029236	total: 400ms	remaining: 1.28s
119:	learn: 0.0029195	total: 403ms	remaining: 1.27s
120:	learn: 0.0029146	total: 407ms	remaining: 1.27s
121:	learn: 0.0029062	total: 409ms	remaining: 1.27s
122:	learn: 0.0029020	total: 413ms	remaining: 1.26s
123:	learn: 0.0028952	total: 416ms	remaining: 1.26s
124:	learn: 0.0028902	total: 420ms	remaining: 1.26s
125:	learn: 0.0028869	total: 423ms	remaining: 1.25s
126:	learn: 0.0028807	total: 427ms	remaining: 1.25s
127:	learn: 0.0028745	total: 431ms	remaining: 1.25s
128:	learn: 0.0028693	total: 434ms	remaining: 1.25s
129:	learn: 0.0028631	total: 439ms	remaining: 1.25s
130:	learn: 0.0028577	total: 442ms	remaining: 1.24s
131:	learn: 0.0028525	total: 445ms	remaining: 1.24s
132:	learn: 0.0028462	total: 450ms	remaining: 1.24s
133:	learn: 0.0028415	total: 453ms	remaining: 1.24s
134:	learn: 0.0028360	total: 457ms	remaining: 1.23s
135:	learn: 0.0028333	total: 460ms	remaining: 1.23s
136:	learn: 0.0028278	total: 464ms	remaining: 1.23s
137:	learn: 0.0028231	total: 466ms	remaining: 1.22s
138:	learn: 0.0028188	total: 470ms	remaining: 1.22s
139:	learn: 0.0028133	total: 473ms	remaining: 1.22s
140:	learn: 0.0028062	total: 476ms	remaining: 1.21s
141:	learn: 0.0028023	total: 479ms	remaining: 1.21s
142:	learn: 0.0027975	total: 483ms	remaining: 1.21s
143:	learn: 0.0027946	total: 486ms	remaining: 1.2s
144:	learn: 0.0027894	total: 489ms	remaining: 1.2s
145:	learn: 0.0027831	total: 493ms	remaining: 1.2s
146:	learn: 0.0027798	total: 496ms	remaining: 1.19s
147:	learn: 0.0027756	total: 499ms	remaining: 1.19s
148:	learn: 0.0027708	total: 504ms	remaining: 1.19s
149:	learn: 0.0027634	total: 507ms	remaining: 1.18s
150:	learn: 0.0027585	total: 510ms	remaining: 1.18s
151:	learn: 0.0027526	total: 514ms	remaining: 1.18s
152:	learn: 0.0027457	total: 518ms	remaining: 1.17s
153:	learn: 0.0027413	total: 522ms	remaining: 1.17s
154:	learn: 0.0027362	total: 525ms	remaining: 1.17s
155:	learn: 0.0027310	total: 529ms	remaining: 1.17s
156:	learn: 0.0027269	total: 532ms	remaining: 1.16s
157:	learn: 0.0027236	total: 536ms	remaining: 1.16s
158:	learn: 0.0027196	total: 540ms	remaining: 1.16s
159:	learn: 0.0027149	total: 544ms	remaining: 1.16s
160:	learn: 0.0027109	total: 547ms	remaining: 1.15s
161:	learn: 0.0027065	total: 551ms	remaining: 1.15s
162:	learn: 0.0027030	total: 556ms	remaining: 1.15s
163:	learn: 0.0026983	total: 559ms	remaining: 1.14s
164:	learn: 0.0026929	total: 562ms	remaining: 1.14s
165:	learn: 0.0026893	total: 565ms	remaining: 1.14s
166:	learn: 0.0026865	total: 569ms	remaining: 1.13s
167:	learn: 0.0026814	total: 572ms	remaining: 1.13s
168:	learn: 0.0026771	total: 577ms	remaining: 1.13s
169:	learn: 0.0026711	total: 580ms	remaining: 1.13s
170:	learn: 0.0026644	total: 584ms	remaining: 1.12s
171:	learn: 0.0026612	total: 589ms	remaining: 1.12s
172:	learn: 0.0026558	total: 592ms	remaining: 1.12s
173:	learn: 0.0026520	total: 596ms	remaining: 1.12s
174:	learn: 0.0026482	total: 600ms	remaining: 1.11s
175:	learn: 0.0026445	total: 604ms	remaining: 1.11s
176:	learn: 0.0026396	total: 608ms	remaining: 1.11s
177:	learn: 0.0026366	total: 611ms	remaining: 1.11s
178:	learn: 0.0026313	total: 615ms	remaining: 1.1s
179:	learn: 0.0026279	total: 620ms	remaining: 1.1s
180:	learn: 0.0026241	total: 623ms	remaining: 1.1s
181:	learn: 0.0026195	total: 626ms	remaining: 1.09s
182:	learn: 0.0026144	total: 631ms	remaining: 1.09s
183:	learn: 0.0026103	total: 635ms	remaining: 1.09s
184:	learn: 0.0026063	total: 640ms	remaining: 1.09s
185:	learn: 0.0026017	total: 643ms	remaining: 1.09s
186:	learn: 0.0025981	total: 647ms	remaining: 1.08s
187:	learn: 0.0025940	total: 650ms	remaining: 1.08s
188:	learn: 0.0025912	total: 653ms	remaining: 1.07s
189:	learn: 0.0025873	total: 656ms	remaining: 1.07s
190:	learn: 0.0025814	total: 660ms	remaining: 1.07s
191:	learn: 0.0025764	total: 664ms	remaining: 1.06s
192:	learn: 0.0025705	total: 667ms	remaining: 1.06s
193:	learn: 0.0025680	total: 671ms	remaining: 1.06s
194:	learn: 0.0025629	total: 675ms	remaining: 1.05s
195:	learn: 0.0025594	total: 678ms	remaining: 1.05s
196:	learn: 0.0025552	total: 682ms	remaining: 1.05s
197:	learn: 0.0025524	total: 686ms	remaining: 1.04s
198:	learn: 0.0025497	total: 722ms	remaining: 1.09s
199:	learn: 0.0025438	total: 726ms	remaining: 1.09s
200:	learn: 0.0025402	total: 729ms	remaining: 1.08s
201:	learn: 0.0025365	total: 732ms	remaining: 1.08s
202:	learn: 0.0025338	total: 736ms	remaining: 1.08s
203:	learn: 0.0025313	total: 740ms	remaining: 1.07s
204:	learn: 0.0025271	total: 743ms	remaining: 1.07s
205:	learn: 0.0025231	total: 747ms	remaining: 1.07s
206:	learn: 0.0025174	total: 750ms	remaining: 1.06s
207:	learn: 0.0025147	total: 753ms	remaining: 1.06s
208:	learn: 0.0025101	total: 758ms	remaining: 1.05s
209:	learn: 0.0025064	total: 761ms	remaining: 1.05s
210:	learn: 0.0025032	total: 765ms	remaining: 1.05s
211:	learn: 0.0025001	total: 768ms	remaining: 1.04s
212:	learn: 0.0024981	total: 772ms	remaining: 1.04s
213:	learn: 0.0024959	total: 778ms	remaining: 1.04s
214:	learn: 0.0024922	total: 781ms	remaining: 1.03s
215:	learn: 0.0024880	total: 784ms	remaining: 1.03s
216:	learn: 0.0024834	total: 789ms	remaining: 1.03s
217:	learn: 0.0024795	total: 793ms	remaining: 1.02s
218:	learn: 0.0024767	total: 796ms	remaining: 1.02s
219:	learn: 0.0024724	total: 800ms	remaining: 1.02s
220:	learn: 0.0024694	total: 804ms	remaining: 1.01s
221:	learn: 0.0024638	total: 808ms	remaining: 1.01s
222:	learn: 0.0024597	total: 813ms	remaining: 1.01s
223:	learn: 0.0024566	total: 816ms	remaining: 1s
224:	learn: 0.0024534	total: 820ms	remaining: 1s
225:	learn: 0.0024498	total: 824ms	remaining: 999ms
226:	learn: 0.0024462	total: 827ms	remaining: 995ms
227:	learn: 0.0024415	total: 831ms	remaining: 992ms
228:	learn: 0.0024370	total: 836ms	remaining: 989ms
229:	learn: 0.0024333	total: 839ms	remaining: 985ms
230:	learn: 0.0024302	total: 844ms	remaining: 983ms
231:	learn: 0.0024278	total: 847ms	remaining: 979ms
232:	learn: 0.0024248	total: 851ms	remaining: 975ms
233:	learn: 0.0024229	total: 855ms	remaining: 972ms
234:	learn: 0.0024195	total: 858ms	remaining: 968ms
235:	learn: 0.0024145	total: 862ms	remaining: 965ms
236:	learn: 0.0024105	total: 866ms	remaining: 961ms
237:	learn: 0.0024085	total: 869ms	remaining: 957ms
238:	learn: 0.0024045	total: 874ms	remaining: 954ms
239:	learn: 0.0024012	total: 878ms	remaining: 951ms
240:	learn: 0.0023966	total: 881ms	remaining: 947ms
241:	learn: 0.0023926	total: 886ms	remaining: 945ms
242:	learn: 0.0023894	total: 890ms	remaining: 941ms
243:	learn: 0.0023865	total: 894ms	remaining: 938ms
244:	learn: 0.0023830	total: 898ms	remaining: 934ms
245:	learn: 0.0023807	total: 901ms	remaining: 930ms
246:	learn: 0.0023769	total: 905ms	remaining: 927ms
247:	learn: 0.0023739	total: 908ms	remaining: 923ms
248:	learn: 0.0023708	total: 913ms	remaining: 920ms
249:	learn: 0.0023670	total: 917ms	remaining: 917ms
250:	learn: 0.0023639	total: 920ms	remaining: 913ms
251:	learn: 0.0023608	total: 924ms	remaining: 909ms
252:	learn: 0.0023566	total: 928ms	remaining: 906ms
253:	learn: 0.0023526	total: 931ms	remaining: 902ms
254:	learn: 0.0023497	total: 936ms	remaining: 899ms
255:	learn: 0.0023468	total: 941ms	remaining: 897ms
256:	learn: 0.0023440	total: 945ms	remaining: 893ms
257:	learn: 0.0023415	total: 949ms	remaining: 890ms
258:	learn: 0.0023390	total: 952ms	remaining: 886ms
259:	learn: 0.0023356	total: 956ms	remaining: 882ms
260:	learn: 0.0023327	total: 959ms	remaining: 878ms
261:	learn: 0.0023295	total: 963ms	remaining: 875ms
262:	learn: 0.0023275	total: 968ms	remaining: 872ms
263:	learn: 0.0023245	total: 972ms	remaining: 869ms
264:	learn: 0.0023223	total: 976ms	remaining: 865ms
265:	learn: 0.0023187	total: 980ms	remaining: 862ms
266:	learn: 0.0023163	total: 984ms	remaining: 858ms
267:	learn: 0.0023133	total: 987ms	remaining: 854ms
268:	learn: 0.0023107	total: 991ms	remaining: 851ms
269:	learn: 0.0023074	total: 994ms	remaining: 847ms
270:	learn: 0.0023058	total: 998ms	remaining: 843ms
271:	learn: 0.0023022	total: 1s	remaining: 840ms
272:	learn: 0.0022998	total: 1s	remaining: 835ms
273:	learn: 0.0022975	total: 1.01s	remaining: 831ms
274:	learn: 0.0022942	total: 1.01s	remaining: 827ms
275:	learn: 0.0022911	total: 1.01s	remaining: 823ms
276:	learn: 0.0022884	total: 1.02s	remaining: 819ms
277:	learn: 0.0022867	total: 1.02s	remaining: 816ms
278:	learn: 0.0022847	total: 1.02s	remaining: 812ms
279:	learn: 0.0022814	total: 1.03s	remaining: 808ms
280:	learn: 0.0022786	total: 1.03s	remaining: 805ms
281:	learn: 0.0022751	total: 1.04s	remaining: 801ms
282:	learn: 0.0022707	total: 1.04s	remaining: 798ms
283:	learn: 0.0022686	total: 1.04s	remaining: 794ms
284:	learn: 0.0022653	total: 1.05s	remaining: 791ms
285:	learn: 0.0022635	total: 1.05s	remaining: 786ms
286:	learn: 0.0022599	total: 1.05s	remaining: 783ms
287:	learn: 0.0022585	total: 1.06s	remaining: 779ms
288:	learn: 0.0022553	total: 1.06s	remaining: 776ms
289:	learn: 0.0022525	total: 1.07s	remaining: 772ms
290:	learn: 0.0022503	total: 1.07s	remaining: 768ms
291:	learn: 0.0022464	total: 1.07s	remaining: 765ms
292:	learn: 0.0022434	total: 1.08s	remaining: 761ms
293:	learn: 0.0022416	total: 1.08s	remaining: 757ms
294:	learn: 0.0022394	total: 1.08s	remaining: 754ms
295:	learn: 0.0022369	total: 1.09s	remaining: 750ms
296:	learn: 0.0022345	total: 1.09s	remaining: 747ms
297:	learn: 0.0022315	total: 1.1s	remaining: 743ms
298:	learn: 0.0022293	total: 1.1s	remaining: 739ms
299:	learn: 0.0022266	total: 1.1s	remaining: 735ms
300:	learn: 0.0022249	total: 1.11s	remaining: 731ms
301:	learn: 0.0022223	total: 1.11s	remaining: 728ms
302:	learn: 0.0022193	total: 1.11s	remaining: 724ms
303:	learn: 0.0022174	total: 1.12s	remaining: 721ms
304:	learn: 0.0022150	total: 1.12s	remaining: 717ms
305:	learn: 0.0022123	total: 1.12s	remaining: 713ms
306:	learn: 0.0022090	total: 1.13s	remaining: 709ms
307:	learn: 0.0022054	total: 1.13s	remaining: 706ms
308:	learn: 0.0022031	total: 1.14s	remaining: 702ms
309:	learn: 0.0022007	total: 1.14s	remaining: 699ms
310:	learn: 0.0021971	total: 1.14s	remaining: 695ms
311:	learn: 0.0021944	total: 1.15s	remaining: 691ms
312:	learn: 0.0021924	total: 1.15s	remaining: 688ms
313:	learn: 0.0021893	total: 1.15s	remaining: 684ms
314:	learn: 0.0021857	total: 1.16s	remaining: 681ms
315:	learn: 0.0021835	total: 1.16s	remaining: 677ms
316:	learn: 0.0021808	total: 1.17s	remaining: 673ms
317:	learn: 0.0021780	total: 1.17s	remaining: 669ms
318:	learn: 0.0021757	total: 1.17s	remaining: 666ms
319:	learn: 0.0021732	total: 1.18s	remaining: 662ms
320:	learn: 0.0021702	total: 1.18s	remaining: 659ms
321:	learn: 0.0021686	total: 1.19s	remaining: 655ms
322:	learn: 0.0021657	total: 1.19s	remaining: 651ms
323:	learn: 0.0021630	total: 1.19s	remaining: 648ms
324:	learn: 0.0021598	total: 1.2s	remaining: 644ms
325:	learn: 0.0021575	total: 1.2s	remaining: 641ms
326:	learn: 0.0021562	total: 1.2s	remaining: 637ms
327:	learn: 0.0021548	total: 1.21s	remaining: 633ms
328:	learn: 0.0021516	total: 1.21s	remaining: 630ms
329:	learn: 0.0021483	total: 1.22s	remaining: 626ms
330:	learn: 0.0021463	total: 1.22s	remaining: 622ms
331:	learn: 0.0021437	total: 1.22s	remaining: 619ms
332:	learn: 0.0021397	total: 1.23s	remaining: 615ms
333:	learn: 0.0021369	total: 1.23s	remaining: 612ms
334:	learn: 0.0021347	total: 1.23s	remaining: 608ms
335:	learn: 0.0021324	total: 1.24s	remaining: 605ms
336:	learn: 0.0021306	total: 1.25s	remaining: 602ms
337:	learn: 0.0021288	total: 1.25s	remaining: 599ms
338:	learn: 0.0021266	total: 1.25s	remaining: 596ms
339:	learn: 0.0021230	total: 1.26s	remaining: 592ms
340:	learn: 0.0021213	total: 1.26s	remaining: 589ms
341:	learn: 0.0021184	total: 1.27s	remaining: 586ms
342:	learn: 0.0021154	total: 1.27s	remaining: 583ms
343:	learn: 0.0021134	total: 1.28s	remaining: 580ms
344:	learn: 0.0021113	total: 1.28s	remaining: 576ms
345:	learn: 0.0021090	total: 1.29s	remaining: 573ms
346:	learn: 0.0021063	total: 1.29s	remaining: 569ms
347:	learn: 0.0021047	total: 1.29s	remaining: 565ms
348:	learn: 0.0021030	total: 1.3s	remaining: 561ms
349:	learn: 0.0021009	total: 1.3s	remaining: 558ms
350:	learn: 0.0020991	total: 1.3s	remaining: 554ms
351:	learn: 0.0020972	total: 1.31s	remaining: 550ms
352:	learn: 0.0020959	total: 1.31s	remaining: 547ms
353:	learn: 0.0020943	total: 1.32s	remaining: 543ms
354:	learn: 0.0020921	total: 1.32s	remaining: 539ms
355:	learn: 0.0020906	total: 1.32s	remaining: 535ms
356:	learn: 0.0020887	total: 1.33s	remaining: 532ms
357:	learn: 0.0020855	total: 1.33s	remaining: 528ms
358:	learn: 0.0020825	total: 1.33s	remaining: 524ms
359:	learn: 0.0020804	total: 1.34s	remaining: 520ms
360:	learn: 0.0020785	total: 1.34s	remaining: 516ms
361:	learn: 0.0020772	total: 1.34s	remaining: 513ms
362:	learn: 0.0020744	total: 1.35s	remaining: 509ms
363:	learn: 0.0020712	total: 1.35s	remaining: 505ms
364:	learn: 0.0020687	total: 1.35s	remaining: 501ms
365:	learn: 0.0020675	total: 1.36s	remaining: 497ms
366:	learn: 0.0020650	total: 1.36s	remaining: 494ms
367:	learn: 0.0020615	total: 1.36s	remaining: 490ms
368:	learn: 0.0020592	total: 1.37s	remaining: 486ms
369:	learn: 0.0020574	total: 1.37s	remaining: 483ms
370:	learn: 0.0020542	total: 1.38s	remaining: 479ms
371:	learn: 0.0020525	total: 1.38s	remaining: 475ms
372:	learn: 0.0020496	total: 1.39s	remaining: 472ms
373:	learn: 0.0020477	total: 1.39s	remaining: 468ms
374:	learn: 0.0020458	total: 1.39s	remaining: 464ms
375:	learn: 0.0020431	total: 1.4s	remaining: 460ms
376:	learn: 0.0020417	total: 1.4s	remaining: 457ms
377:	learn: 0.0020389	total: 1.4s	remaining: 453ms
378:	learn: 0.0020375	total: 1.41s	remaining: 449ms
379:	learn: 0.0020352	total: 1.41s	remaining: 445ms
380:	learn: 0.0020326	total: 1.41s	remaining: 442ms
381:	learn: 0.0020298	total: 1.42s	remaining: 438ms
382:	learn: 0.0020284	total: 1.42s	remaining: 434ms
383:	learn: 0.0020259	total: 1.43s	remaining: 431ms
384:	learn: 0.0020248	total: 1.43s	remaining: 427ms
385:	learn: 0.0020229	total: 1.43s	remaining: 423ms
386:	learn: 0.0020210	total: 1.44s	remaining: 420ms