In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error

In [44]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [45]:
df = pd.read_csv('../data/processed/dataset_long.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
df.head()

,datetime,underlying_price,contract,iv,option_type,strike,hour,minute,day_of_week,date,session_progress,days_to_expiry,moneyness,log_moneyness,dist_from_atm,dist_from_atm_pct,is_ce,strike_rank,iv_neighbor_-2,iv_neighbor_-1,iv_neighbor_+1,iv_neighbor_+2,iv_neighbor_mean,wide_iv_neighbor_mean,iv_lag_1,iv_roll_mean_5,iv_roll_std_5,iv_roll_mean_10,mean_ce_iv,mean_pe_iv
0,2026-01-07 09:15:00,26111.65,NIFTY27JAN2625200CE,0.12662,CE,25200,9,15,2,2026-01-07,4860.0,20.2569,0.965086,-0.035538,911.65,0.034914,1,0.0,NaN,NaN,0.12330,0.11741,0.12330,0.11741,NaN,NaN,NaN,NaN,0.102447,0.102447
1,2026-01-07 09:20:00,26141.40,NIFTY27JAN2625200CE,0.08632,CE,25200,9,20,2,2026-01-07,4865.0,20.2535,0.963988,-0.036676,941.40,0.036012,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.12662,NaN,NaN,NaN,0.098723,0.098723
2,2026-01-07 09:25:00,26139.35,NIFTY27JAN2625200CE,0.09147,CE,25200,9,25,2,2026-01-07,4870.0,20.2500,0.964064,-0.036598,939.35,0.035936,1,0.0,NaN,NaN,NaN,0.09514,NaN,0.09514,0.08632,0.106470,0.028496,NaN,0.091074,0.091074
3,2026-01-07 09:30:00,26128.95,NIFTY27JAN2625200CE,0.10860,CE,25200,9,30,2,2026-01-07,4875.0,20.2465,0.964447,-0.036200,928.95,0.035553,1,0.0,NaN,NaN,0.10842,0.11150,0.10842,0.11150,0.09147,0.101470,0.021932,0.101470,0.103252,0.103252
4,2026-01-07 09:35:00,26131.90,NIFTY27JAN2625200CE,0.10462,CE,25200,9,35,2,2026-01-07,4880.0,20.2431,0.964339,-0.036313,931.90,0.035661,1,0.0,NaN,NaN,0.10538,0.12459,0.10538,0.12459,0.10860,0.103252,0.018259,0.103252,0.104097,0.104097

In [46]:
df.columns

Index(['datetime', 'underlying_price', 'contract', 'iv', 'option_type',
       'strike', 'hour', 'minute', 'day_of_week', 'date', 'session_progress',
       'days_to_expiry', 'moneyness', 'log_moneyness', 'dist_from_atm',
       'dist_from_atm_pct', 'is_ce', 'strike_rank', 'iv_neighbor_-2',
       'iv_neighbor_-1', 'iv_neighbor_+1', 'iv_neighbor_+2',
       'iv_neighbor_mean', 'wide_iv_neighbor_mean', 'iv_lag_1',
       'iv_roll_mean_5', 'iv_roll_std_5', 'iv_roll_mean_10', 'mean_ce_iv',
       'mean_pe_iv'],
      dtype='str')

In [52]:
trading_days = sorted(df['datetime'].dt.date.unique())

folds = [
    {'name': 'fold1', 'train_dates': dates[:8],  'val_dates': dates[8:10]},
    {'name': 'fold2', 'train_dates': dates[:10], 'val_dates': dates[10:12]},
]

In [48]:
def make_holdout(val_df,random_state=2):
    np.random.seed(42)

    available_rows = val_df[val_df['iv'].notna()].index

    hidden_rows = np.random.choice(available_rows,size=int(0.2*len(available_rows)),replace=False)

    ground_truth = val_df.loc[hidden_rows,'iv'].values

    val_masked = val_df.copy()

    val_masked.loc[hidden_rows,'iv'] = np.nan

    return val_masked,hidden_rows,ground_truth

In [49]:
# evaluation functions for ml models
def eval_pred(actual,predicted):
    valid = ~np.isnan(predicted)

    mse = mean_squared_error(actual[valid],predicted[valid])
    coverage = valid.mean()

    print(f"MSE: {mse:6f}")
    print(f"Coverage: {coverage:6f}")

    return mse,coverage

In [64]:
import xgboost
import lightgbm
import catboost

### Model 1: XGBoost will all features

In [54]:
from xgboost import XGBRegressor

fold_mses, fold_coverages, feature_importances = [],[],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df[df['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df[df['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)
    feature_importances.append(xgb_model.feature_importances_)

print(f"xgb_mse: {np.mean(fold_mses):6f}")
print(f"xgb_coverage: {np.mean(fold_coverages):6f}")
print(f"feature importances: {feature_importances}")

MSE: 0.000114
Coverage: 1.000000
MSE: 0.000047
Coverage: 1.000000
xgb_mse: 0.000081
xgb_coverage: 1.000000
feature importances: [array([0.0042983 , 0.01186388, 0.00338471, 0.00345063, 0.00715866,
       0.00499231, 0.00423238, 0.0098574 , 0.00816558, 0.00841981,
       0.01185304, 0.        , 0.01034581, 0.00874176, 0.01494427,
       0.02264537, 0.02140105, 0.4981133 , 0.05849594, 0.00520056,
       0.22881566, 0.00379396, 0.02297753, 0.01251369, 0.01433442],
      dtype=float32), array([0.00247129, 0.00621403, 0.00108871, 0.00110867, 0.00310131,
       0.00215398, 0.00219415, 0.02390117, 0.00368832, 0.0064261 ,
       0.00643909, 0.0005458 , 0.00393209, 0.00472965, 0.00666619,
       0.0132345 , 0.00542649, 0.26722205, 0.03958256, 0.00331858,
       0.49992165, 0.00180436, 0.07908553, 0.00519456, 0.01054917],
      dtype=float32)]

In [59]:
avg_importance = np.mean(feature_importances,axis=0)

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': avg_importance
})

importance_df = importance_df.sort_values(by='importance',ascending=False)

importance_df

                  feature  importance
17       iv_neighbor_mean    0.382668
20         iv_roll_mean_5    0.364369
22        iv_roll_mean_10    0.051032
18  wide_iv_neighbor_mean    0.049039
15         iv_neighbor_+1    0.017940
7               moneyness    0.016879
16         iv_neighbor_+2    0.013414
24             mean_pe_iv    0.012442
14         iv_neighbor_-1    0.010805
10      dist_from_atm_pct    0.009146
1                  strike    0.009039
23             mean_ce_iv    0.008854
9           dist_from_atm    0.007423
12            strike_rank    0.007139
13         iv_neighbor_-2    0.006736
8           log_moneyness    0.005927
4             day_of_week    0.005130
19               iv_lag_1    0.004260
5        session_progress    0.003573
0        underlying_price    0.003385
6          days_to_expiry    0.003213
21          iv_roll_std_5    0.002799
3                  minute    0.002280
2                    hour    0.002237
11                  is_ce    0.000273

In [60]:
selected_features = importance_df[importance_df['importance']>=0.005]['feature'].tolist()

selected_features

['iv_neighbor_mean',
 'iv_roll_mean_5',
 'iv_roll_mean_10',
 'wide_iv_neighbor_mean',
 'iv_neighbor_+1',
 'moneyness',
 'iv_neighbor_+2',
 'mean_pe_iv',
 'iv_neighbor_-1',
 'dist_from_atm_pct',
 'strike',
 'mean_ce_iv',
 'dist_from_atm',
 'strike_rank',
 'iv_neighbor_-2',
 'log_moneyness',
 'day_of_week']

In [61]:
df_pruned = df[selected_features+['iv','contract','option_type','date','datetime']].copy()
print(df_pruned.shape)
df_pruned.head()

(27300, 22)

,iv_neighbor_mean,iv_roll_mean_5,iv_roll_mean_10,wide_iv_neighbor_mean,iv_neighbor_+1,moneyness,iv_neighbor_+2,mean_pe_iv,iv_neighbor_-1,dist_from_atm_pct,strike,mean_ce_iv,dist_from_atm,strike_rank,iv_neighbor_-2,log_moneyness,day_of_week,iv,contract,option_type,date,datetime
0,0.12330,NaN,NaN,0.11741,0.12330,0.965086,0.11741,0.102447,NaN,0.034914,25200,0.102447,911.65,0.0,NaN,-0.035538,2,0.12662,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:15:00
1,NaN,NaN,NaN,NaN,NaN,0.963988,NaN,0.098723,NaN,0.036012,25200,0.098723,941.40,0.0,NaN,-0.036676,2,0.08632,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:20:00
2,NaN,0.106470,NaN,0.09514,NaN,0.964064,0.09514,0.091074,NaN,0.035936,25200,0.091074,939.35,0.0,NaN,-0.036598,2,0.09147,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:25:00
3,0.10842,0.101470,0.101470,0.11150,0.10842,0.964447,0.11150,0.103252,NaN,0.035553,25200,0.103252,928.95,0.0,NaN,-0.036200,2,0.10860,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:30:00
4,0.10538,0.103252,0.103252,0.12459,0.10538,0.964339,0.12459,0.104097,NaN,0.035661,25200,0.104097,931.90,0.0,NaN,-0.036313,2,0.10462,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:35:00

In [62]:
df_pruned.to_csv('../data/processed/dataset_long_pruned.csv',index=False)

### Model 2: XGBoost with pruned features

In [63]:
fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)

print(f"xgbp_mse: {np.mean(fold_mses):6f}")
print(f"xgbp_coverage: {np.mean(fold_coverages):6f}")

MSE: 0.000104
Coverage: 1.000000
MSE: 0.000033
Coverage: 1.000000
xgbp_mse: 0.000069
xgbp_coverage: 1.000000

### Model 3: LightGBM

In [71]:
from lightgbm import LGBMRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    lgbm_model = LGBMRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    lgbm_model.fit(X_train,y_train)
    lgbm_pred = lgbm_model.predict(X_val)

    lgbm_mse, lgbm_coverage = eval_pred(ground_truth,lgbm_pred)

    fold_mses.append(lgbm_mse)
    fold_coverages.append(lgbm_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"lgbm_mse: {np.mean(fold_mses):6f}")
print(f"lgbm_coverage: {np.mean(fold_coverages):6f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001111 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3598
[LightGBM] [Info] Number of data points in the train set: 13496, number of used features: 17
[LightGBM] [Info] Start training from score 0.106715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
MSE: 0.000097
Coverage: 1.000000
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3604
[LightGBM] [Info] Number of data points in the train set: 16882, number of used features: 17
[LightGBM] [Info] Start training from score 0.111642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Model 4: CatBoost

In [75]:
from catboost import CatBoostRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    cb_model = CatBoostRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        random_state= 2,
    )

    cb_model.fit(X_train,y_train)
    cb_pred = cb_model.predict(X_val)

    cb_mse, cb_coverage = eval_pred(ground_truth,cb_pred)

    fold_mses.append(cb_mse)
    fold_coverages.append(cb_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"cb_mse: {np.mean(fold_mses):6f}")
print(f"cb_coverage: {np.mean(fold_coverages):6f}")

0:	learn: 0.0120786	total: 164ms	remaining: 1m 21s
1:	learn: 0.0116134	total: 174ms	remaining: 43.2s
2:	learn: 0.0111750	total: 182ms	remaining: 30.1s
3:	learn: 0.0107577	total: 191ms	remaining: 23.7s
4:	learn: 0.0103597	total: 198ms	remaining: 19.6s
5:	learn: 0.0099842	total: 205ms	remaining: 16.9s
6:	learn: 0.0096301	total: 211ms	remaining: 14.9s
7:	learn: 0.0092875	total: 218ms	remaining: 13.4s
8:	learn: 0.0089566	total: 227ms	remaining: 12.4s
9:	learn: 0.0086560	total: 234ms	remaining: 11.5s
10:	learn: 0.0083585	total: 242ms	remaining: 10.8s
11:	learn: 0.0080878	total: 249ms	remaining: 10.1s
12:	learn: 0.0078296	total: 254ms	remaining: 9.53s
13:	learn: 0.0075801	total: 260ms	remaining: 9.04s
14:	learn: 0.0073521	total: 265ms	remaining: 8.58s
15:	learn: 0.0071296	total: 271ms	remaining: 8.21s
16:	learn: 0.0069189	total: 276ms	remaining: 7.85s
17:	learn: 0.0067197	total: 282ms	remaining: 7.55s
18:	learn: 0.0065286	total: 286ms	remaining: 7.25s
19:	learn: 0.0063502	total: 291ms	remaining: 6.98s
20:	learn: 0.0061688	total: 296ms	remaining: 6.75s
21:	learn: 0.0060112	total: 300ms	remaining: 6.52s
22:	learn: 0.0058553	total: 304ms	remaining: 6.3s
23:	learn: 0.0057064	total: 309ms	remaining: 6.12s
24:	learn: 0.0055699	total: 313ms	remaining: 5.95s
25:	learn: 0.0054429	total: 317ms	remaining: 5.78s
26:	learn: 0.0053216	total: 322ms	remaining: 5.64s
27:	learn: 0.0052053	total: 327ms	remaining: 5.51s
28:	learn: 0.0050981	total: 331ms	remaining: 5.38s
29:	learn: 0.0049919	total: 335ms	remaining: 5.25s
30:	learn: 0.0048946	total: 339ms	remaining: 5.13s
31:	learn: 0.0048017	total: 343ms	remaining: 5.02s
32:	learn: 0.0047110	total: 347ms	remaining: 4.91s
33:	learn: 0.0046360	total: 351ms	remaining: 4.81s
34:	learn: 0.0045571	total: 355ms	remaining: 4.72s
35:	learn: 0.0044798	total: 360ms	remaining: 4.64s
36:	learn: 0.0044128	total: 364ms	remaining: 4.56s
37:	learn: 0.0043442	total: 369ms	remaining: 4.49s
38:	learn: 0.0042845	total: 374ms	remaining: 4.42s
39:	learn: 0.0042209	total: 377ms	remaining: 4.34s
40:	learn: 0.0041626	total: 382ms	remaining: 4.28s
41:	learn: 0.0041088	total: 387ms	remaining: 4.22s
42:	learn: 0.0040540	total: 393ms	remaining: 4.18s
43:	learn: 0.0040064	total: 399ms	remaining: 4.13s
44:	learn: 0.0039583	total: 405ms	remaining: 4.09s
45:	learn: 0.0039155	total: 409ms	remaining: 4.03s
46:	learn: 0.0038788	total: 414ms	remaining: 3.99s
47:	learn: 0.0038398	total: 418ms	remaining: 3.94s
48:	learn: 0.0038045	total: 422ms	remaining: 3.89s
49:	learn: 0.0037720	total: 427ms	remaining: 3.84s
50:	learn: 0.0037427	total: 431ms	remaining: 3.79s
51:	learn: 0.0037127	total: 436ms	remaining: 3.75s
52:	learn: 0.0036838	total: 440ms	remaining: 3.71s
53:	learn: 0.0036540	total: 445ms	remaining: 3.67s
54:	learn: 0.0036274	total: 449ms	remaining: 3.63s
55:	learn: 0.0036033	total: 454ms	remaining: 3.6s
56:	learn: 0.0035806	total: 459ms	remaining: 3.57s
57:	learn: 0.0035563	total: 463ms	remaining: 3.53s
58:	learn: 0.0035354	total: 468ms	remaining: 3.5s
59:	learn: 0.0035173	total: 472ms	remaining: 3.46s
60:	learn: 0.0034962	total: 477ms	remaining: 3.43s
61:	learn: 0.0034793	total: 481ms	remaining: 3.4s
62:	learn: 0.0034622	total: 485ms	remaining: 3.36s
63:	learn: 0.0034422	total: 489ms	remaining: 3.33s
64:	learn: 0.0034226	total: 493ms	remaining: 3.3s
65:	learn: 0.0034054	total: 498ms	remaining: 3.27s
66:	learn: 0.0033858	total: 502ms	remaining: 3.24s
67:	learn: 0.0033716	total: 506ms	remaining: 3.21s
68:	learn: 0.0033599	total: 510ms	remaining: 3.19s
69:	learn: 0.0033462	total: 514ms	remaining: 3.15s
70:	learn: 0.0033303	total: 518ms	remaining: 3.13s
71:	learn: 0.0033173	total: 522ms	remaining: 3.1s
72:	learn: 0.0033032	total: 526ms	remaining: 3.08s
73:	learn: 0.0032887	total: 531ms	remaining: 3.06s
74:	learn: 0.0032762	total: 535ms	remaining: 3.03s
75:	learn: 0.0032653	total: 539ms	remaining: 3.01s
76:	learn: 0.0032533	total: 544ms	remaining: 2.99s
77:	learn: 0.0032420	total: 548ms	remaining: 2.96s
78:	learn: 0.0032321	total: 551ms	remaining: 2.94s
79:	learn: 0.0032196	total: 555ms	remaining: 2.91s
80:	learn: 0.0032091	total: 559ms	remaining: 2.89s
81:	learn: 0.0031997	total: 563ms	remaining: 2.87s
82:	learn: 0.0031881	total: 567ms	remaining: 2.85s
83:	learn: 0.0031791	total: 571ms	remaining: 2.83s
84:	learn: 0.0031694	total: 577ms	remaining: 2.82s
85:	learn: 0.0031565	total: 616ms	remaining: 2.96s
86:	learn: 0.0031468	total: 620ms	remaining: 2.94s
87:	learn: 0.0031371	total: 625ms	remaining: 2.92s
88:	learn: 0.0031288	total: 629ms	remaining: 2.9s
89:	learn: 0.0031209	total: 633ms	remaining: 2.88s
90:	learn: 0.0031125	total: 638ms	remaining: 2.87s
91:	learn: 0.0031055	total: 642ms	remaining: 2.85s
92:	learn: 0.0030973	total: 647ms	remaining: 2.83s
93:	learn: 0.0030880	total: 650ms	remaining: 2.81s
94:	learn: 0.0030793	total: 655ms	remaining: 2.79s
95:	learn: 0.0030702	total: 659ms	remaining: 2.77s
96:	learn: 0.0030644	total: 663ms	remaining: 2.75s
97:	learn: 0.0030552	total: 667ms	remaining: 2.73s
98:	learn: 0.0030472	total: 671ms	remaining: 2.72s
99:	learn: 0.0030378	total: 675ms	remaining: 2.7s
100:	learn: 0.0030296	total: 679ms	remaining: 2.68s
101:	learn: 0.0030201	total: 683ms	remaining: 2.67s
102:	learn: 0.0030125	total: 687ms	remaining: 2.65s
103:	learn: 0.0030068	total: 691ms	remaining: 2.63s
104:	learn: 0.0029992	total: 696ms	remaining: 2.62s
105:	learn: 0.0029928	total: 700ms	remaining: 2.6s
106:	learn: 0.0029827	total: 704ms	remaining: 2.58s
107:	learn: 0.0029778	total: 708ms	remaining: 2.57s
108:	learn: 0.0029705	total: 712ms	remaining: 2.55s
109:	learn: 0.0029631	total: 716ms	remaining: 2.54s
110:	learn: 0.0029555	total: 721ms	remaining: 2.52s
111:	learn: 0.0029480	total: 725ms	remaining: 2.51s
112:	learn: 0.0029420	total: 729ms	remaining: 2.5s
113:	learn: 0.0029361	total: 733ms	remaining: 2.48s
114:	learn: 0.0029284	total: 738ms	remaining: 2.47s
115:	learn: 0.0029214	total: 742ms	remaining: 2.46s
116:	learn: 0.0029150	total: 746ms	remaining: 2.44s
117:	learn: 0.0029096	total: 749ms	remaining: 2.43s
118:	learn: 0.0029028	total: 754ms	remaining: 2.42s
119:	learn: 0.0028971	total: 759ms	remaining: 2.4s
120:	learn: 0.0028895	total: 763ms	remaining: 2.39s
121:	learn: 0.0028830	total: 767ms	remaining: 2.38s
122:	learn: 0.0028786	total: 772ms	remaining: 2.37s
123:	learn: 0.0028736	total: 777ms	remaining: 2.35s
124:	learn: 0.0028668	total: 781ms	remaining: 2.34s
125:	learn: 0.0028582	total: 787ms	remaining: 2.34s
126:	learn: 0.0028508	total: 791ms	remaining: 2.32s
127:	learn: 0.0028437	total: 796ms	remaining: 2.31s
128:	learn: 0.0028382	total: 802ms	remaining: 2.31s
129:	learn: 0.0028326	total: 806ms	remaining: 2.29s
130:	learn: 0.0028274	total: 811ms	remaining: 2.28s
131:	learn: 0.0028231	total: 816ms	remaining: 2.27s
132:	learn: 0.0028169	total: 821ms	remaining: 2.26s
133:	learn: 0.0028124	total: 825ms	remaining: 2.25s
134:	learn: 0.0028066	total: 829ms	remaining: 2.24s
135:	learn: 0.0028013	total: 833ms	remaining: 2.23s
136:	learn: 0.0027958	total: 837ms	remaining: 2.22s
137:	learn: 0.0027904	total: 842ms	remaining: 2.21s
138:	learn: 0.0027859	total: 846ms	remaining: 2.2s
139:	learn: 0.0027789	total: 851ms	remaining: 2.19s
140:	learn: 0.0027744	total: 854ms	remaining: 2.17s
141:	learn: 0.0027724	total: 859ms	remaining: 2.16s
142:	learn: 0.0027657	total: 863ms	remaining: 2.15s
143:	learn: 0.0027605	total: 867ms	remaining: 2.14s
144:	learn: 0.0027561	total: 871ms	remaining: 2.13s
145:	learn: 0.0027513	total: 876ms	remaining: 2.12s
146:	learn: 0.0027442	total: 880ms	remaining: 2.11s
147:	learn: 0.0027383	total: 884ms	remaining: 2.1s
148:	learn: 0.0027343	total: 888ms	remaining: 2.09s
149:	learn: 0.0027288	total: 892ms	remaining: 2.08s
150:	learn: 0.0027250	total: 897ms	remaining: 2.07s
151:	learn: 0.0027207	total: 901ms	remaining: 2.06s
152:	learn: 0.0027156	total: 905ms	remaining: 2.05s
153:	learn: 0.0027094	total: 909ms	remaining: 2.04s
154:	learn: 0.0027035	total: 913ms	remaining: 2.03s
155:	learn: 0.0026988	total: 918ms	remaining: 2.02s
156:	learn: 0.0026936	total: 923ms	remaining: 2.02s
157:	learn: 0.0026892	total: 927ms	remaining: 2.01s
158:	learn: 0.0026837	total: 931ms	remaining: 2s
159:	learn: 0.0026796	total: 936ms	remaining: 1.99s
160:	learn: 0.0026737	total: 940ms	remaining: 1.98s
161:	learn: 0.0026701	total: 945ms	remaining: 1.97s
162:	learn: 0.0026654	total: 949ms	remaining: 1.96s
163:	learn: 0.0026604	total: 953ms	remaining: 1.95s
164:	learn: 0.0026549	total: 957ms	remaining: 1.94s
165:	learn: 0.0026521	total: 961ms	remaining: 1.93s
166:	learn: 0.0026469	total: 967ms	remaining: 1.93s
167:	learn: 0.0026418	total: 971ms	remaining: 1.92s
168:	learn: 0.0026375	total: 976ms	remaining: 1.91s
169:	learn: 0.0026336	total: 980ms	remaining: 1.9s
170:	learn: 0.0026272	total: 984ms	remaining: 1.89s
171:	learn: 0.0026196	total: 988ms	remaining: 1.88s
172:	learn: 0.0026135	total: 994ms	remaining: 1.88s
173:	learn: 0.0026114	total: 999ms	remaining: 1.87s
174:	learn: 0.0026068	total: 1s	remaining: 1.86s
175:	learn: 0.0026013	total: 1.01s	remaining: 1.85s
176:	learn: 0.0025979	total: 1.01s	remaining: 1.85s
177:	learn: 0.0025928	total: 1.02s	remaining: 1.84s
178:	learn: 0.0025893	total: 1.02s	remaining: 1.83s
179:	learn: 0.0025849	total: 1.02s	remaining: 1.82s
180:	learn: 0.0025814	total: 1.03s	remaining: 1.81s
181:	learn: 0.0025761	total: 1.03s	remaining: 1.8s
182:	learn: 0.0025725	total: 1.03s	remaining: 1.79s
183:	learn: 0.0025672	total: 1.04s	remaining: 1.79s
184:	learn: 0.0025635	total: 1.04s	remaining: 1.78s
185:	learn: 0.0025587	total: 1.05s	remaining: 1.77s
186:	learn: 0.0025550	total: 1.05s	remaining: 1.76s
187:	learn: 0.0025502	total: 1.06s	remaining: 1.75s
188:	learn: 0.0025470	total: 1.06s	remaining: 1.75s
189:	learn: 0.0025421	total: 1.06s	remaining: 1.74s
190:	learn: 0.0025385	total: 1.07s	remaining: 1.73s
191:	learn: 0.0025319	total: 1.07s	remaining: 1.72s
192:	learn: 0.0025278	total: 1.08s	remaining: 1.71s
193:	learn: 0.0025248	total: 1.08s	remaining: 1.7s
194:	learn: 0.0025219	total: 1.08s	remaining: 1.7s
195:	learn: 0.0025162	total: 1.09s	remaining: 1.69s
196:	learn: 0.0025123	total: 1.09s	remaining: 1.68s
197:	learn: 0.0025095	total: 1.1s	remaining: 1.67s
198:	learn: 0.0025059	total: 1.1s	remaining: 1.66s
199:	learn: 0.0025027	total: 1.1s	remaining: 1.66s
200:	learn: 0.0024990	total: 1.11s	remaining: 1.65s
201:	learn: 0.0024939	total: 1.11s	remaining: 1.64s
202:	learn: 0.0024894	total: 1.12s	remaining: 1.64s
203:	learn: 0.0024850	total: 1.12s	remaining: 1.63s
204:	learn: 0.0024813	total: 1.13s	remaining: 1.62s
205:	learn: 0.0024759	total: 1.13s	remaining: 1.61s
206:	learn: 0.0024716	total: 1.14s	remaining: 1.61s
207:	learn: 0.0024677	total: 1.14s	remaining: 1.6s
208:	learn: 0.0024660	total: 1.14s	remaining: 1.59s
209:	learn: 0.0024627	total: 1.15s	remaining: 1.58s
210:	learn: 0.0024584	total: 1.15s	remaining: 1.58s
211:	learn: 0.0024525	total: 1.16s	remaining: 1.57s
212:	learn: 0.0024483	total: 1.16s	remaining: 1.56s
213:	learn: 0.0024450	total: 1.16s	remaining: 1.55s
214:	learn: 0.0024404	total: 1.17s	remaining: 1.55s
215:	learn: 0.0024375	total: 1.17s	remaining: 1.54s
216:	learn: 0.0024330	total: 1.18s	remaining: 1.53s
217:	learn: 0.0024291	total: 1.18s	remaining: 1.53s
218:	learn: 0.0024249	total: 1.18s	remaining: 1.52s
219:	learn: 0.0024207	total: 1.19s	remaining: 1.51s
220:	learn: 0.0024151	total: 1.19s	remaining: 1.51s
221:	learn: 0.0024126	total: 1.2s	remaining: 1.5s
222:	learn: 0.0024091	total: 1.2s	remaining: 1.49s
223:	learn: 0.0024061	total: 1.21s	remaining: 1.49s
224:	learn: 0.0024014	total: 1.22s	remaining: 1.49s
225:	learn: 0.0023984	total: 1.22s	remaining: 1.48s
226:	learn: 0.0023944	total: 1.23s	remaining: 1.47s
227:	learn: 0.0023889	total: 1.23s	remaining: 1.47s
228:	learn: 0.0023840	total: 1.23s	remaining: 1.46s
229:	learn: 0.0023790	total: 1.24s	remaining: 1.45s
230:	learn: 0.0023742	total: 1.24s	remaining: 1.45s
231:	learn: 0.0023714	total: 1.25s	remaining: 1.44s
232:	learn: 0.0023676	total: 1.25s	remaining: 1.43s
233:	learn: 0.0023642	total: 1.25s	remaining: 1.43s
234:	learn: 0.0023608	total: 1.26s	remaining: 1.42s
235:	learn: 0.0023578	total: 1.26s	remaining: 1.41s
236:	learn: 0.0023557	total: 1.27s	remaining: 1.41s
237:	learn: 0.0023517	total: 1.27s	remaining: 1.4s
238:	learn: 0.0023476	total: 1.27s	remaining: 1.39s
239:	learn: 0.0023440	total: 1.28s	remaining: 1.39s
240:	learn: 0.0023416	total: 1.28s	remaining: 1.38s
241:	learn: 0.0023384	total: 1.29s	remaining: 1.37s
242:	learn: 0.0023350	total: 1.29s	remaining: 1.36s
243:	learn: 0.0023318	total: 1.3s	remaining: 1.36s
244:	learn: 0.0023285	total: 1.3s	remaining: 1.35s
245:	learn: 0.0023248	total: 1.31s	remaining: 1.35s
246:	learn: 0.0023229	total: 1.31s	remaining: 1.34s
247:	learn: 0.0023196	total: 1.31s	remaining: 1.34s
248:	learn: 0.0023157	total: 1.32s	remaining: 1.33s
249:	learn: 0.0023131	total: 1.32s	remaining: 1.32s
250:	learn: 0.0023091	total: 1.33s	remaining: 1.32s
251:	learn: 0.0023040	total: 1.33s	remaining: 1.31s
252:	learn: 0.0022993	total: 1.33s	remaining: 1.3s
253:	learn: 0.0022965	total: 1.34s	remaining: 1.3s
254:	learn: 0.0022940	total: 1.34s	remaining: 1.29s
255:	learn: 0.0022906	total: 1.35s	remaining: 1.28s
256:	learn: 0.0022878	total: 1.35s	remaining: 1.28s
257:	learn: 0.0022837	total: 1.35s	remaining: 1.27s
258:	learn: 0.0022803	total: 1.36s	remaining: 1.26s
259:	learn: 0.0022766	total: 1.36s	remaining: 1.26s
260:	learn: 0.0022746	total: 1.37s	remaining: 1.25s
261:	learn: 0.0022721	total: 1.37s	remaining: 1.25s
262:	learn: 0.0022697	total: 1.37s	remaining: 1.24s
263:	learn: 0.0022661	total: 1.38s	remaining: 1.23s
264:	learn: 0.0022631	total: 1.38s	remaining: 1.23s
265:	learn: 0.0022588	total: 1.39s	remaining: 1.22s
266:	learn: 0.0022558	total: 1.39s	remaining: 1.22s
267:	learn: 0.0022529	total: 1.4s	remaining: 1.21s
268:	learn: 0.0022501	total: 1.4s	remaining: 1.2s
269:	learn: 0.0022474	total: 1.41s	remaining: 1.2s
270:	learn: 0.0022440	total: 1.41s	remaining: 1.19s
271:	learn: 0.0022418	total: 1.42s	remaining: 1.19s
272:	learn: 0.0022385	total: 1.43s	remaining: 1.19s
273:	learn: 0.0022349	total: 1.43s	remaining: 1.18s
274:	learn: 0.0022318	total: 1.44s	remaining: 1.17s
275:	learn: 0.0022286	total: 1.44s	remaining: 1.17s
276:	learn: 0.0022260	total: 1.44s	remaining: 1.16s
277:	learn: 0.0022217	total: 1.45s	remaining: 1.16s
278:	learn: 0.0022179	total: 1.45s	remaining: 1.15s
279:	learn: 0.0022145	total: 1.46s	remaining: 1.15s
280:	learn: 0.0022118	total: 1.46s	remaining: 1.14s
281:	learn: 0.0022085	total: 1.47s	remaining: 1.13s
282:	learn: 0.0022059	total: 1.47s	remaining: 1.13s
283:	learn: 0.0022034	total: 1.48s	remaining: 1.12s
284:	learn: 0.0022003	total: 1.48s	remaining: 1.12s
285:	learn: 0.0021960	total: 1.49s	remaining: 1.11s
286:	learn: 0.0021933	total: 1.49s	remaining: 1.11s
287:	learn: 0.0021896	total: 1.5s	remaining: 1.1s
288:	learn: 0.0021883	total: 1.5s	remaining: 1.09s
289:	learn: 0.0021852	total: 1.5s	remaining: 1.09s
290:	learn: 0.0021811	total: 1.51s	remaining: 1.08s
291:	learn: 0.0021799	total: 1.51s	remaining: 1.08s
292:	learn: 0.0021773	total: 1.52s	remaining: 1.07s
293:	learn: 0.0021726	total: 1.52s	remaining: 1.07s
294:	learn: 0.0021698	total: 1.53s	remaining: 1.06s
295:	learn: 0.0021663	total: 1.53s	remaining: 1.05s
296:	learn: 0.0021630	total: 1.53s	remaining: 1.05s
297:	learn: 0.0021605	total: 1.54s	remaining: 1.04s
298:	learn: 0.0021575	total: 1.54s	remaining: 1.04s
299:	learn: 0.0021548	total: 1.55s	remaining: 1.03s
300:	learn: 0.0021512	total: 1.55s	remaining: 1.03s
301:	learn: 0.0021470	total: 1.56s	remaining: 1.02s
302:	learn: 0.0021450	total: 1.56s	remaining: 1.02s
303:	learn: 0.0021415	total: 1.57s	remaining: 1.01s
304:	learn: 0.0021380	total: 1.57s	remaining: 1s
305:	learn: 0.0021357	total: 1.58s	remaining: 1000ms
306:	learn: 0.0021333	total: 1.58s	remaining: 994ms
307:	learn: 0.0021301	total: 1.58s	remaining: 989ms
308:	learn: 0.0021274	total: 1.59s	remaining: 984ms
309:	learn: 0.0021245	total: 1.6s	remaining: 978ms
310:	learn: 0.0021224	total: 1.6s	remaining: 973ms
311:	learn: 0.0021201	total: 1.6s	remaining: 967ms
312:	learn: 0.0021179	total: 1.61s	remaining: 962ms
313:	learn: 0.0021146	total: 1.61s	remaining: 956ms
314:	learn: 0.0021124	total: 1.62s	remaining: 951ms
315:	learn: 0.0021103	total: 1.63s	remaining: 946ms
316:	learn: 0.0021083	total: 1.63s	remaining: 941ms
317:	learn: 0.0021066	total: 1.63s	remaining: 936ms
318:	learn: 0.0021036	total: 1.64s	remaining: 930ms
319:	learn: 0.0021008	total: 1.64s	remaining: 925ms
320:	learn: 0.0020976	total: 1.65s	remaining: 919ms
321:	learn: 0.0020961	total: 1.65s	remaining: 914ms
322:	learn: 0.0020932	total: 1.66s	remaining: 908ms
323:	learn: 0.0020903	total: 1.66s	remaining: 903ms
324:	learn: 0.0020877	total: 1.67s	remaining: 897ms
325:	learn: 0.0020850	total: 1.67s	remaining: 892ms
326:	learn: 0.0020834	total: 1.68s	remaining: 886ms
327:	learn: 0.0020814	total: 1.68s	remaining: 881ms
328:	learn: 0.0020783	total: 1.68s	remaining: 875ms
329:	learn: 0.0020752	total: 1.69s	remaining: 870ms
330:	learn: 0.0020727	total: 1.69s	remaining: 865ms
331:	learn: 0.0020708	total: 1.7s	remaining: 860ms
332:	learn: 0.0020672	total: 1.7s	remaining: 854ms
333:	learn: 0.0020644	total: 1.71s	remaining: 849ms
334:	learn: 0.0020611	total: 1.71s	remaining: 843ms
335:	learn: 0.0020579	total: 1.72s	remaining: 838ms
336:	learn: 0.0020553	total: 1.72s	remaining: 832ms
337:	learn: 0.0020541	total: 1.73s	remaining: 827ms
338:	learn: 0.0020521	total: 1.73s	remaining: 822ms
339:	learn: 0.0020502	total: 1.73s	remaining: 816ms
340:	learn: 0.0020475	total: 1.74s	remaining: 811ms
341:	learn: 0.0020449	total: 1.74s	remaining: 806ms
342:	learn: 0.0020413	total: 1.75s	remaining: 800ms
343:	learn: 0.0020384	total: 1.75s	remaining: 795ms
344:	learn: 0.0020363	total: 1.76s	remaining: 789ms
345:	learn: 0.0020328	total: 1.76s	remaining: 784ms
346:	learn: 0.0020297	total: 1.76s	remaining: 778ms
347:	learn: 0.0020271	total: 1.77s	remaining: 773ms
348:	learn: 0.0020248	total: 1.77s	remaining: 768ms
349:	learn: 0.0020216	total: 1.78s	remaining: 763ms
350:	learn: 0.0020182	total: 1.78s	remaining: 758ms
351:	learn: 0.0020167	total: 1.79s	remaining: 752ms
352:	learn: 0.0020143	total: 1.79s	remaining: 747ms
353:	learn: 0.0020121	total: 1.8s	remaining: 742ms
354:	learn: 0.0020107	total: 1.8s	remaining: 736ms
355:	learn: 0.0020075	total: 1.81s	remaining: 731ms
356:	learn: 0.0020055	total: 1.81s	remaining: 726ms
357:	learn: 0.0020038	total: 1.82s	remaining: 721ms
358:	learn: 0.0020014	total: 1.82s	remaining: 716ms
359:	learn: 0.0020001	total: 1.83s	remaining: 711ms
360:	learn: 0.0019981	total: 1.83s	remaining: 705ms
361:	learn: 0.0019962	total: 1.84s	remaining: 700ms
362:	learn: 0.0019942	total: 1.84s	remaining: 695ms
363:	learn: 0.0019921	total: 1.84s	remaining: 690ms
364:	learn: 0.0019898	total: 1.85s	remaining: 684ms
365:	learn: 0.0019874	total: 1.85s	remaining: 679ms
366:	learn: 0.0019844	total: 1.86s	remaining: 673ms
367:	learn: 0.0019829	total: 1.86s	remaining: 668ms
368:	learn: 0.0019814	total: 1.87s	remaining: 663ms
369:	learn: 0.0019791	total: 1.87s	remaining: 658ms
370:	learn: 0.0019775	total: 1.88s	remaining: 653ms
371:	learn: 0.0019746	total: 1.88s	remaining: 647ms
372:	learn: 0.0019732	total: 1.89s	remaining: 642ms
373:	learn: 0.0019713	total: 1.89s	remaining: 637ms
374:	learn: 0.0019686	total: 1.89s	remaining: 631ms
375:	learn: 0.0019660	total: 1.9s	remaining: 626ms
376:	learn: 0.0019646	total: 1.9s	remaining: 621ms
377:	learn: 0.0019619	total: 1.92s	remaining: 619ms
378:	learn: 0.0019592	total: 1.92s	remaining: 614ms
379:	learn: 0.0019571	total: 1.93s	remaining: 609ms
380:	learn: 0.0019541	total: 1.93s	remaining: 604ms
381:	learn: 0.0019522	total: 1.94s	remaining: 598ms
382:	learn: 0.0019489	total: 1.94s	remaining: 593ms
383:	learn: 0.0019473	total: 1.95s	remaining: 588ms
384:	learn: 0.0019447	total: 1.95s	remaining: 583ms
385:	learn: 0.0019425	total: 1.96s	remaining: 577ms
386:	learn: 0.0019414	total: 1.96s	remaining: 572ms