In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv('../data/processed/dataset_long.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
df.head()

,datetime,underlying_price,contract,iv,option_type,strike,hour,minute,day_of_week,date,session_progress,days_to_expiry,moneyness,log_moneyness,dist_from_atm,dist_from_atm_pct,is_ce,strike_rank,iv_neighbor_-2,iv_neighbor_-1,iv_neighbor_+1,iv_neighbor_+2,iv_neighbor_mean,wide_iv_neighbor_mean,iv_lag_1,iv_roll_mean_5,iv_roll_std_5,iv_roll_mean_10,mean_ce_iv,mean_pe_iv
0,2026-01-07 09:15:00,26111.65,NIFTY27JAN2625200CE,0.12662,CE,25200,9,15,2,2026-01-07,0.000000,20.2569,0.965086,-0.035538,911.65,0.034914,1,0.0,NaN,NaN,0.12330,0.11741,0.12330,0.11741,NaN,NaN,NaN,NaN,0.102447,0.143129
1,2026-01-07 09:20:00,26141.40,NIFTY27JAN2625200CE,0.08632,CE,25200,9,20,2,2026-01-07,0.013514,20.2535,0.963988,-0.036676,941.40,0.036012,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.12662,NaN,NaN,NaN,0.098723,0.147267
2,2026-01-07 09:25:00,26139.35,NIFTY27JAN2625200CE,0.09147,CE,25200,9,25,2,2026-01-07,0.027027,20.2500,0.964064,-0.036598,939.35,0.035936,1,0.0,NaN,NaN,NaN,0.09514,NaN,0.09514,0.08632,0.106470,0.028496,NaN,0.091074,0.148739
3,2026-01-07 09:30:00,26128.95,NIFTY27JAN2625200CE,0.10860,CE,25200,9,30,2,2026-01-07,0.040541,20.2465,0.964447,-0.036200,928.95,0.035553,1,0.0,NaN,NaN,0.10842,0.11150,0.10842,0.11150,0.09147,0.101470,0.021932,0.101470,0.103252,0.142787
4,2026-01-07 09:35:00,26131.90,NIFTY27JAN2625200CE,0.10462,CE,25200,9,35,2,2026-01-07,0.054054,20.2431,0.964339,-0.036313,931.90,0.035661,1,0.0,NaN,NaN,0.10538,0.12459,0.10538,0.12459,0.10860,0.103252,0.018259,0.103252,0.104097,0.147425

In [4]:
df['iv'].isna().sum()

np.int64(5460)

In [5]:
df.columns

Index(['datetime', 'underlying_price', 'contract', 'iv', 'option_type',
       'strike', 'hour', 'minute', 'day_of_week', 'date', 'session_progress',
       'days_to_expiry', 'moneyness', 'log_moneyness', 'dist_from_atm',
       'dist_from_atm_pct', 'is_ce', 'strike_rank', 'iv_neighbor_-2',
       'iv_neighbor_-1', 'iv_neighbor_+1', 'iv_neighbor_+2',
       'iv_neighbor_mean', 'wide_iv_neighbor_mean', 'iv_lag_1',
       'iv_roll_mean_5', 'iv_roll_std_5', 'iv_roll_mean_10', 'mean_ce_iv',
       'mean_pe_iv'],
      dtype='str')

In [6]:
dates = sorted(df['datetime'].dt.date.unique())

folds = [
    {'name': 'Fold 1', 'train_dates': dates[:9],  'val_dates': dates[9:11]},
    {'name': 'Fold 2', 'train_dates': dates[:10], 'val_dates': dates[10:12]},
]

In [12]:
def make_holdout(val_df):
    np.random.seed(42)

    available_rows = val_df[val_df['iv'].notna()].index

    hidden_rows = np.random.choice(available_rows,size=int(0.2*len(available_rows)),replace=False)

    ground_truth = val_df.loc[hidden_rows,'iv'].values

    val_masked = val_df.copy()

    val_masked.loc[hidden_rows,'iv'] = np.nan

    return val_masked,hidden_rows,ground_truth

In [8]:
# evaluation functions for ml models
def eval_pred(actual,predicted):
    valid = ~np.isnan(predicted)

    mse = mean_squared_error(actual[valid],predicted[valid])
    coverage = valid.mean()

    print(f"MSE: {mse:6f}")
    print(f"Coverage: {coverage:6f}")

    return mse,coverage

In [9]:
import xgboost
import lightgbm
import catboost

### Model 1: XGBoost will all features

In [10]:
from xgboost import XGBRegressor

fold_mses, fold_coverages, feature_importances = [],[],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df[df['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df[df['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)
    feature_importances.append(xgb_model.feature_importances_)

print(f"xgb_mse: {np.mean(fold_mses):6f}")
print(f"xgb_coverage: {np.mean(fold_coverages):6f}")
print(f"feature importances: {feature_importances}")

MSE: 0.000070
Coverage: 1.000000
MSE: 0.000027
Coverage: 1.000000
xgb_mse: 0.000049
xgb_coverage: 1.000000
feature importances: [array([3.7790253e-04, 6.5848730e-03, 2.6073269e-04, 3.1602397e-04,
       4.4758245e-04, 4.6028820e-04, 3.8273609e-04, 1.2178053e-03,
       1.3457789e-03, 9.0239325e-04, 1.5925937e-03, 2.8371465e-04,
       9.9229719e-04, 1.3220002e-03, 2.3099901e-03, 3.7963623e-03,
       2.2564763e-03, 6.9269374e-02, 8.1679281e-03, 9.1375475e-04,
       1.8787275e-01, 5.5386731e-04, 7.0740551e-01, 5.5702927e-04,
       4.1024093e-04], dtype=float32), array([3.5593307e-04, 3.0944557e-03, 1.8743968e-04, 2.4557763e-04,
       4.8874796e-04, 4.1361374e-04, 4.1689051e-04, 1.2898707e-03,
       1.0478845e-03, 6.4841594e-04, 1.0786148e-03, 7.0529344e-04,
       9.3577954e-04, 1.3852600e-03, 1.9683843e-03, 3.3845291e-03,
       1.8066594e-03, 6.0578205e-02, 7.7353991e-03, 1.0245242e-03,
       2.3247994e-01, 5.5427814e-04, 6.7727518e-01, 5.1713292e-04,
       3.8206877e-04], dtype=float32)]

In [17]:
avg_importance = np.mean(feature_importances,axis=0)

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': avg_importance
})

importance_df = importance_df.sort_values(by='importance',ascending=False)

importance_df

                  feature  importance
22        iv_roll_mean_10    0.692340
20         iv_roll_mean_5    0.210176
17       iv_neighbor_mean    0.064924
18  wide_iv_neighbor_mean    0.007952
1                  strike    0.004840
15         iv_neighbor_+1    0.003590
14         iv_neighbor_-1    0.002139
16         iv_neighbor_+2    0.002032
13         iv_neighbor_-2    0.001354
10      dist_from_atm_pct    0.001336
7               moneyness    0.001254
8           log_moneyness    0.001197
19               iv_lag_1    0.000969
12            strike_rank    0.000964
9           dist_from_atm    0.000775
21          iv_roll_std_5    0.000554
23             mean_ce_iv    0.000537
11                  is_ce    0.000495
4             day_of_week    0.000468
5        session_progress    0.000437
6          days_to_expiry    0.000400
24             mean_pe_iv    0.000396
0        underlying_price    0.000367
3                  minute    0.000281
2                    hour    0.000224

In [18]:
selected_features = importance_df[importance_df['importance']>=0.001]['feature'].tolist()

selected_features

['iv_roll_mean_10',
 'iv_roll_mean_5',
 'iv_neighbor_mean',
 'wide_iv_neighbor_mean',
 'strike',
 'iv_neighbor_+1',
 'iv_neighbor_-1',
 'iv_neighbor_+2',
 'iv_neighbor_-2',
 'dist_from_atm_pct',
 'moneyness',
 'log_moneyness']

In [19]:
df_pruned = df[selected_features+['iv','contract','option_type','date','datetime']].copy()
print(df_pruned.shape)
df_pruned.head()

(27300, 17)

,iv_roll_mean_10,iv_roll_mean_5,iv_neighbor_mean,wide_iv_neighbor_mean,strike,iv_neighbor_+1,iv_neighbor_-1,iv_neighbor_+2,iv_neighbor_-2,dist_from_atm_pct,moneyness,log_moneyness,iv,contract,option_type,date,datetime
0,NaN,NaN,0.12330,0.11741,25200,0.12330,NaN,0.11741,NaN,0.034914,0.965086,-0.035538,0.12662,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:15:00
1,NaN,NaN,NaN,NaN,25200,NaN,NaN,NaN,NaN,0.036012,0.963988,-0.036676,0.08632,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:20:00
2,NaN,0.106470,NaN,0.09514,25200,NaN,NaN,0.09514,NaN,0.035936,0.964064,-0.036598,0.09147,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:25:00
3,0.101470,0.101470,0.10842,0.11150,25200,0.10842,NaN,0.11150,NaN,0.035553,0.964447,-0.036200,0.10860,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:30:00
4,0.103252,0.103252,0.10538,0.12459,25200,0.10538,NaN,0.12459,NaN,0.035661,0.964339,-0.036313,0.10462,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:35:00

In [20]:
df_pruned['iv'].isna().sum()

np.int64(5460)

In [21]:
df_pruned.to_csv('../data/processed/dataset_long_pruned.csv',index=False)

### Model 2: XGBoost with pruned features

In [22]:
fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)

print(f"xgbp_mse: {np.mean(fold_mses):6f}")
print(f"xgbp_coverage: {np.mean(fold_coverages):6f}")

MSE: 0.000067
Coverage: 1.000000
MSE: 0.000023
Coverage: 1.000000
xgbp_mse: 0.000045
xgbp_coverage: 1.000000

### Model 3: LightGBM

In [23]:
from lightgbm import LGBMRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    lgbm_model = LGBMRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    lgbm_model.fit(X_train,y_train)
    lgbm_pred = lgbm_model.predict(X_val)

    lgbm_mse, lgbm_coverage = eval_pred(ground_truth,lgbm_pred)

    fold_mses.append(lgbm_mse)
    fold_coverages.append(lgbm_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"lgbm_mse: {np.mean(fold_mses):6f}")
print(f"lgbm_coverage: {np.mean(fold_coverages):6f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004757 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2834
[LightGBM] [Info] Number of data points in the train set: 15089, number of used features: 12
[LightGBM] [Info] Start training from score 0.129295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Model 4: CatBoost

In [24]:
from catboost import CatBoostRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    cb_model = CatBoostRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        random_state= 2,
    )

    cb_model.fit(X_train,y_train)
    cb_pred = cb_model.predict(X_val)

    cb_mse, cb_coverage = eval_pred(ground_truth,cb_pred)

    fold_mses.append(cb_mse)
    fold_coverages.append(cb_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"cb_mse: {np.mean(fold_mses):6f}")
print(f"cb_coverage: {np.mean(fold_coverages):6f}")

0:	learn: 0.0285783	total: 173ms	remaining: 1m 26s
1:	learn: 0.0272713	total: 185ms	remaining: 46.1s
2:	learn: 0.0260105	total: 195ms	remaining: 32.2s
3:	learn: 0.0248180	total: 202ms	remaining: 25s
4:	learn: 0.0236856	total: 212ms	remaining: 21s
5:	learn: 0.0226357	total: 219ms	remaining: 18s
6:	learn: 0.0216363	total: 225ms	remaining: 15.9s
7:	learn: 0.0206699	total: 233ms	remaining: 14.3s
8:	learn: 0.0197516	total: 242ms	remaining: 13.2s
9:	learn: 0.0188914	total: 251ms	remaining: 12.3s
10:	learn: 0.0180568	total: 258ms	remaining: 11.5s
11:	learn: 0.0172762	total: 265ms	remaining: 10.8s
12:	learn: 0.0165296	total: 272ms	remaining: 10.2s
13:	learn: 0.0158327	total: 278ms	remaining: 9.65s
14:	learn: 0.0151552	total: 284ms	remaining: 9.18s
15:	learn: 0.0145105	total: 291ms	remaining: 8.81s
16:	learn: 0.0138960	total: 298ms	remaining: 8.48s
17:	learn: 0.0133114	total: 305ms	remaining: 8.15s
18:	learn: 0.0127474	total: 310ms	remaining: 7.85s
19:	learn: 0.0122314	total: 315ms	remaining: 7.57s
20:	learn: 0.0117370	total: 321ms	remaining: 7.33s
21:	learn: 0.0112721	total: 326ms	remaining: 7.09s
22:	learn: 0.0108288	total: 332ms	remaining: 6.88s
23:	learn: 0.0104093	total: 336ms	remaining: 6.66s
24:	learn: 0.0100073	total: 340ms	remaining: 6.47s
25:	learn: 0.0096253	total: 345ms	remaining: 6.3s
26:	learn: 0.0092569	total: 349ms	remaining: 6.12s
27:	learn: 0.0089239	total: 354ms	remaining: 5.97s
28:	learn: 0.0086043	total: 359ms	remaining: 5.82s
29:	learn: 0.0082930	total: 364ms	remaining: 5.7s
30:	learn: 0.0079890	total: 368ms	remaining: 5.57s
31:	learn: 0.0077108	total: 372ms	remaining: 5.45s
32:	learn: 0.0074576	total: 377ms	remaining: 5.34s
33:	learn: 0.0072182	total: 383ms	remaining: 5.24s
34:	learn: 0.0069872	total: 387ms	remaining: 5.14s
35:	learn: 0.0067675	total: 392ms	remaining: 5.05s
36:	learn: 0.0065659	total: 397ms	remaining: 4.96s
37:	learn: 0.0063688	total: 401ms	remaining: 4.87s
38:	learn: 0.0061801	total: 405ms	remaining: 4.79s
39:	learn: 0.0060054	total: 410ms	remaining: 4.71s
40:	learn: 0.0058379	total: 414ms	remaining: 4.64s
41:	learn: 0.0056807	total: 420ms	remaining: 4.58s
42:	learn: 0.0055368	total: 424ms	remaining: 4.51s
43:	learn: 0.0054010	total: 429ms	remaining: 4.45s
44:	learn: 0.0052679	total: 434ms	remaining: 4.39s
45:	learn: 0.0051455	total: 439ms	remaining: 4.33s
46:	learn: 0.0050358	total: 444ms	remaining: 4.28s
47:	learn: 0.0049345	total: 448ms	remaining: 4.22s
48:	learn: 0.0048347	total: 453ms	remaining: 4.17s
49:	learn: 0.0047382	total: 458ms	remaining: 4.12s
50:	learn: 0.0046555	total: 462ms	remaining: 4.07s
51:	learn: 0.0045623	total: 467ms	remaining: 4.02s
52:	learn: 0.0044874	total: 471ms	remaining: 3.97s
53:	learn: 0.0044108	total: 476ms	remaining: 3.93s
54:	learn: 0.0043476	total: 480ms	remaining: 3.88s
55:	learn: 0.0042857	total: 485ms	remaining: 3.84s
56:	learn: 0.0042183	total: 488ms	remaining: 3.79s
57:	learn: 0.0041607	total: 493ms	remaining: 3.76s
58:	learn: 0.0041125	total: 498ms	remaining: 3.72s
59:	learn: 0.0040631	total: 503ms	remaining: 3.69s
60:	learn: 0.0040170	total: 507ms	remaining: 3.65s
61:	learn: 0.0039746	total: 512ms	remaining: 3.62s
62:	learn: 0.0039245	total: 517ms	remaining: 3.58s
63:	learn: 0.0038778	total: 521ms	remaining: 3.55s
64:	learn: 0.0038443	total: 525ms	remaining: 3.52s
65:	learn: 0.0038055	total: 530ms	remaining: 3.49s
66:	learn: 0.0037649	total: 536ms	remaining: 3.46s
67:	learn: 0.0037309	total: 540ms	remaining: 3.43s
68:	learn: 0.0037009	total: 544ms	remaining: 3.4s
69:	learn: 0.0036744	total: 549ms	remaining: 3.37s
70:	learn: 0.0036516	total: 553ms	remaining: 3.34s
71:	learn: 0.0036259	total: 558ms	remaining: 3.31s
72:	learn: 0.0036046	total: 562ms	remaining: 3.29s
73:	learn: 0.0035824	total: 576ms	remaining: 3.32s
74:	learn: 0.0035611	total: 581ms	remaining: 3.29s
75:	learn: 0.0035407	total: 585ms	remaining: 3.26s
76:	learn: 0.0035243	total: 589ms	remaining: 3.24s
77:	learn: 0.0035038	total: 594ms	remaining: 3.21s
78:	learn: 0.0034831	total: 598ms	remaining: 3.19s
79:	learn: 0.0034666	total: 604ms	remaining: 3.17s
80:	learn: 0.0034522	total: 608ms	remaining: 3.15s
81:	learn: 0.0034356	total: 613ms	remaining: 3.12s
82:	learn: 0.0034191	total: 617ms	remaining: 3.1s
83:	learn: 0.0034049	total: 622ms	remaining: 3.08s
84:	learn: 0.0033907	total: 626ms	remaining: 3.06s
85:	learn: 0.0033733	total: 631ms	remaining: 3.04s
86:	learn: 0.0033538	total: 635ms	remaining: 3.02s
87:	learn: 0.0033404	total: 640ms	remaining: 3s
88:	learn: 0.0033293	total: 645ms	remaining: 2.98s
89:	learn: 0.0033197	total: 649ms	remaining: 2.96s
90:	learn: 0.0033053	total: 654ms	remaining: 2.94s
91:	learn: 0.0032924	total: 658ms	remaining: 2.92s
92:	learn: 0.0032771	total: 663ms	remaining: 2.9s
93:	learn: 0.0032646	total: 668ms	remaining: 2.88s
94:	learn: 0.0032533	total: 673ms	remaining: 2.87s
95:	learn: 0.0032425	total: 677ms	remaining: 2.85s
96:	learn: 0.0032352	total: 681ms	remaining: 2.83s
97:	learn: 0.0032236	total: 686ms	remaining: 2.81s
98:	learn: 0.0032158	total: 690ms	remaining: 2.79s
99:	learn: 0.0032066	total: 696ms	remaining: 2.78s
100:	learn: 0.0031988	total: 700ms	remaining: 2.77s
101:	learn: 0.0031889	total: 705ms	remaining: 2.75s
102:	learn: 0.0031783	total: 709ms	remaining: 2.73s
103:	learn: 0.0031707	total: 714ms	remaining: 2.72s
104:	learn: 0.0031599	total: 718ms	remaining: 2.7s
105:	learn: 0.0031498	total: 722ms	remaining: 2.69s
106:	learn: 0.0031415	total: 727ms	remaining: 2.67s
107:	learn: 0.0031334	total: 731ms	remaining: 2.65s
108:	learn: 0.0031282	total: 736ms	remaining: 2.64s
109:	learn: 0.0031217	total: 740ms	remaining: 2.63s
110:	learn: 0.0031161	total: 745ms	remaining: 2.61s
111:	learn: 0.0031057	total: 749ms	remaining: 2.6s
112:	learn: 0.0030950	total: 754ms	remaining: 2.58s
113:	learn: 0.0030861	total: 758ms	remaining: 2.57s
114:	learn: 0.0030802	total: 763ms	remaining: 2.55s
115:	learn: 0.0030750	total: 767ms	remaining: 2.54s
116:	learn: 0.0030700	total: 773ms	remaining: 2.53s
117:	learn: 0.0030655	total: 778ms	remaining: 2.52s
118:	learn: 0.0030574	total: 782ms	remaining: 2.5s
119:	learn: 0.0030532	total: 787ms	remaining: 2.49s
120:	learn: 0.0030481	total: 792ms	remaining: 2.48s
121:	learn: 0.0030442	total: 795ms	remaining: 2.46s
122:	learn: 0.0030393	total: 801ms	remaining: 2.45s
123:	learn: 0.0030341	total: 805ms	remaining: 2.44s
124:	learn: 0.0030249	total: 810ms	remaining: 2.43s
125:	learn: 0.0030192	total: 815ms	remaining: 2.42s
126:	learn: 0.0030152	total: 819ms	remaining: 2.41s
127:	learn: 0.0030064	total: 824ms	remaining: 2.39s
128:	learn: 0.0029978	total: 828ms	remaining: 2.38s
129:	learn: 0.0029901	total: 833ms	remaining: 2.37s
130:	learn: 0.0029853	total: 838ms	remaining: 2.36s
131:	learn: 0.0029806	total: 842ms	remaining: 2.35s
132:	learn: 0.0029749	total: 846ms	remaining: 2.33s
133:	learn: 0.0029676	total: 851ms	remaining: 2.33s
134:	learn: 0.0029639	total: 856ms	remaining: 2.31s
135:	learn: 0.0029582	total: 861ms	remaining: 2.3s
136:	learn: 0.0029517	total: 865ms	remaining: 2.29s
137:	learn: 0.0029444	total: 870ms	remaining: 2.28s
138:	learn: 0.0029384	total: 875ms	remaining: 2.27s
139:	learn: 0.0029344	total: 880ms	remaining: 2.26s
140:	learn: 0.0029319	total: 884ms	remaining: 2.25s
141:	learn: 0.0029276	total: 889ms	remaining: 2.24s
142:	learn: 0.0029195	total: 894ms	remaining: 2.23s
143:	learn: 0.0029121	total: 898ms	remaining: 2.22s
144:	learn: 0.0029047	total: 903ms	remaining: 2.21s
145:	learn: 0.0029011	total: 907ms	remaining: 2.2s
146:	learn: 0.0028947	total: 911ms	remaining: 2.19s
147:	learn: 0.0028901	total: 916ms	remaining: 2.18s
148:	learn: 0.0028836	total: 921ms	remaining: 2.17s
149:	learn: 0.0028806	total: 926ms	remaining: 2.16s
150:	learn: 0.0028737	total: 931ms	remaining: 2.15s
151:	learn: 0.0028690	total: 936ms	remaining: 2.14s
152:	learn: 0.0028661	total: 941ms	remaining: 2.13s
153:	learn: 0.0028601	total: 946ms	remaining: 2.13s
154:	learn: 0.0028571	total: 951ms	remaining: 2.12s
155:	learn: 0.0028508	total: 957ms	remaining: 2.11s
156:	learn: 0.0028451	total: 961ms	remaining: 2.1s
157:	learn: 0.0028386	total: 966ms	remaining: 2.09s
158:	learn: 0.0028338	total: 971ms	remaining: 2.08s
159:	learn: 0.0028281	total: 977ms	remaining: 2.08s
160:	learn: 0.0028249	total: 982ms	remaining: 2.07s
161:	learn: 0.0028225	total: 986ms	remaining: 2.06s
162:	learn: 0.0028167	total: 991ms	remaining: 2.05s
163:	learn: 0.0028142	total: 995ms	remaining: 2.04s
164:	learn: 0.0028118	total: 1000ms	remaining: 2.03s
165:	learn: 0.0028085	total: 1s	remaining: 2.02s
166:	learn: 0.0028008	total: 1.01s	remaining: 2.01s
167:	learn: 0.0027981	total: 1.01s	remaining: 2s
168:	learn: 0.0027944	total: 1.02s	remaining: 1.99s
169:	learn: 0.0027896	total: 1.02s	remaining: 1.98s
170:	learn: 0.0027835	total: 1.03s	remaining: 1.98s
171:	learn: 0.0027788	total: 1.03s	remaining: 1.97s
172:	learn: 0.0027746	total: 1.04s	remaining: 1.96s
173:	learn: 0.0027687	total: 1.04s	remaining: 1.95s
174:	learn: 0.0027661	total: 1.04s	remaining: 1.94s
175:	learn: 0.0027622	total: 1.05s	remaining: 1.93s
176:	learn: 0.0027597	total: 1.05s	remaining: 1.93s
177:	learn: 0.0027568	total: 1.06s	remaining: 1.92s
178:	learn: 0.0027521	total: 1.06s	remaining: 1.91s
179:	learn: 0.0027466	total: 1.07s	remaining: 1.9s
180:	learn: 0.0027416	total: 1.07s	remaining: 1.89s
181:	learn: 0.0027395	total: 1.08s	remaining: 1.88s
182:	learn: 0.0027373	total: 1.08s	remaining: 1.88s
183:	learn: 0.0027350	total: 1.09s	remaining: 1.87s
184:	learn: 0.0027324	total: 1.09s	remaining: 1.86s
185:	learn: 0.0027265	total: 1.1s	remaining: 1.85s
186:	learn: 0.0027237	total: 1.1s	remaining: 1.84s
187:	learn: 0.0027194	total: 1.11s	remaining: 1.84s
188:	learn: 0.0027140	total: 1.11s	remaining: 1.83s
189:	learn: 0.0027103	total: 1.11s	remaining: 1.82s
190:	learn: 0.0027068	total: 1.12s	remaining: 1.81s
191:	learn: 0.0027026	total: 1.13s	remaining: 1.8s
192:	learn: 0.0026985	total: 1.13s	remaining: 1.8s
193:	learn: 0.0026954	total: 1.13s	remaining: 1.79s
194:	learn: 0.0026938	total: 1.14s	remaining: 1.78s
195:	learn: 0.0026910	total: 1.14s	remaining: 1.77s
196:	learn: 0.0026879	total: 1.15s	remaining: 1.76s
197:	learn: 0.0026850	total: 1.15s	remaining: 1.75s
198:	learn: 0.0026806	total: 1.16s	remaining: 1.75s
199:	learn: 0.0026758	total: 1.16s	remaining: 1.74s
200:	learn: 0.0026714	total: 1.17s	remaining: 1.73s
201:	learn: 0.0026683	total: 1.17s	remaining: 1.73s
202:	learn: 0.0026646	total: 1.18s	remaining: 1.72s
203:	learn: 0.0026587	total: 1.18s	remaining: 1.71s
204:	learn: 0.0026565	total: 1.19s	remaining: 1.71s
205:	learn: 0.0026526	total: 1.19s	remaining: 1.7s
206:	learn: 0.0026479	total: 1.2s	remaining: 1.69s
207:	learn: 0.0026454	total: 1.2s	remaining: 1.69s
208:	learn: 0.0026407	total: 1.21s	remaining: 1.68s
209:	learn: 0.0026383	total: 1.21s	remaining: 1.67s
210:	learn: 0.0026336	total: 1.22s	remaining: 1.66s
211:	learn: 0.0026315	total: 1.22s	remaining: 1.66s
212:	learn: 0.0026265	total: 1.22s	remaining: 1.65s
213:	learn: 0.0026214	total: 1.23s	remaining: 1.64s
214:	learn: 0.0026191	total: 1.23s	remaining: 1.63s
215:	learn: 0.0026162	total: 1.24s	remaining: 1.63s
216:	learn: 0.0026131	total: 1.24s	remaining: 1.62s
217:	learn: 0.0026098	total: 1.25s	remaining: 1.61s
218:	learn: 0.0026063	total: 1.25s	remaining: 1.6s
219:	learn: 0.0026027	total: 1.25s	remaining: 1.6s
220:	learn: 0.0026005	total: 1.26s	remaining: 1.59s
221:	learn: 0.0025973	total: 1.26s	remaining: 1.58s
222:	learn: 0.0025954	total: 1.27s	remaining: 1.57s
223:	learn: 0.0025932	total: 1.27s	remaining: 1.57s
224:	learn: 0.0025904	total: 1.28s	remaining: 1.56s
225:	learn: 0.0025876	total: 1.28s	remaining: 1.55s
226:	learn: 0.0025858	total: 1.29s	remaining: 1.55s
227:	learn: 0.0025814	total: 1.29s	remaining: 1.54s
228:	learn: 0.0025774	total: 1.29s	remaining: 1.53s
229:	learn: 0.0025759	total: 1.3s	remaining: 1.53s
230:	learn: 0.0025734	total: 1.3s	remaining: 1.52s
231:	learn: 0.0025695	total: 1.31s	remaining: 1.51s
232:	learn: 0.0025675	total: 1.31s	remaining: 1.5s
233:	learn: 0.0025632	total: 1.32s	remaining: 1.5s
234:	learn: 0.0025596	total: 1.32s	remaining: 1.49s
235:	learn: 0.0025553	total: 1.33s	remaining: 1.48s
236:	learn: 0.0025528	total: 1.33s	remaining: 1.48s
237:	learn: 0.0025507	total: 1.34s	remaining: 1.47s
238:	learn: 0.0025493	total: 1.34s	remaining: 1.46s
239:	learn: 0.0025474	total: 1.34s	remaining: 1.46s
240:	learn: 0.0025451	total: 1.35s	remaining: 1.45s
241:	learn: 0.0025407	total: 1.35s	remaining: 1.44s
242:	learn: 0.0025391	total: 1.36s	remaining: 1.44s
243:	learn: 0.0025357	total: 1.36s	remaining: 1.43s
244:	learn: 0.0025314	total: 1.37s	remaining: 1.42s
245:	learn: 0.0025292	total: 1.37s	remaining: 1.42s
246:	learn: 0.0025279	total: 1.38s	remaining: 1.41s
247:	learn: 0.0025257	total: 1.38s	remaining: 1.4s
248:	learn: 0.0025237	total: 1.39s	remaining: 1.4s
249:	learn: 0.0025187	total: 1.39s	remaining: 1.39s
250:	learn: 0.0025164	total: 1.41s	remaining: 1.4s
251:	learn: 0.0025150	total: 1.42s	remaining: 1.39s
252:	learn: 0.0025125	total: 1.42s	remaining: 1.39s
253:	learn: 0.0025107	total: 1.42s	remaining: 1.38s
254:	learn: 0.0025076	total: 1.43s	remaining: 1.37s
255:	learn: 0.0025042	total: 1.43s	remaining: 1.36s
256:	learn: 0.0025004	total: 1.44s	remaining: 1.36s
257:	learn: 0.0024960	total: 1.44s	remaining: 1.35s
258:	learn: 0.0024943	total: 1.45s	remaining: 1.34s
259:	learn: 0.0024898	total: 1.45s	remaining: 1.34s
260:	learn: 0.0024883	total: 1.45s	remaining: 1.33s
261:	learn: 0.0024854	total: 1.46s	remaining: 1.33s
262:	learn: 0.0024834	total: 1.46s	remaining: 1.32s
263:	learn: 0.0024814	total: 1.47s	remaining: 1.31s
264:	learn: 0.0024768	total: 1.47s	remaining: 1.31s
265:	learn: 0.0024743	total: 1.48s	remaining: 1.3s
266:	learn: 0.0024723	total: 1.48s	remaining: 1.29s
267:	learn: 0.0024685	total: 1.49s	remaining: 1.29s
268:	learn: 0.0024671	total: 1.49s	remaining: 1.28s
269:	learn: 0.0024642	total: 1.5s	remaining: 1.27s
270:	learn: 0.0024608	total: 1.5s	remaining: 1.27s
271:	learn: 0.0024579	total: 1.51s	remaining: 1.26s
272:	learn: 0.0024542	total: 1.51s	remaining: 1.26s
273:	learn: 0.0024528	total: 1.52s	remaining: 1.25s
274:	learn: 0.0024485	total: 1.52s	remaining: 1.24s
275:	learn: 0.0024447	total: 1.53s	remaining: 1.24s
276:	learn: 0.0024428	total: 1.53s	remaining: 1.23s
277:	learn: 0.0024389	total: 1.54s	remaining: 1.23s
278:	learn: 0.0024358	total: 1.54s	remaining: 1.22s
279:	learn: 0.0024335	total: 1.55s	remaining: 1.21s
280:	learn: 0.0024316	total: 1.55s	remaining: 1.21s
281:	learn: 0.0024303	total: 1.55s	remaining: 1.2s
282:	learn: 0.0024273	total: 1.56s	remaining: 1.2s
283:	learn: 0.0024258	total: 1.56s	remaining: 1.19s
284:	learn: 0.0024238	total: 1.57s	remaining: 1.18s
285:	learn: 0.0024222	total: 1.57s	remaining: 1.18s
286:	learn: 0.0024196	total: 1.58s	remaining: 1.17s
287:	learn: 0.0024172	total: 1.58s	remaining: 1.16s
288:	learn: 0.0024156	total: 1.59s	remaining: 1.16s
289:	learn: 0.0024135	total: 1.59s	remaining: 1.15s
290:	learn: 0.0024098	total: 1.6s	remaining: 1.15s
291:	learn: 0.0024073	total: 1.6s	remaining: 1.14s
292:	learn: 0.0024041	total: 1.61s	remaining: 1.14s
293:	learn: 0.0024026	total: 1.61s	remaining: 1.13s
294:	learn: 0.0024011	total: 1.62s	remaining: 1.12s
295:	learn: 0.0023988	total: 1.62s	remaining: 1.12s
296:	learn: 0.0023953	total: 1.63s	remaining: 1.11s
297:	learn: 0.0023917	total: 1.63s	remaining: 1.1s
298:	learn: 0.0023884	total: 1.63s	remaining: 1.1s
299:	learn: 0.0023857	total: 1.64s	remaining: 1.09s
300:	learn: 0.0023848	total: 1.64s	remaining: 1.09s
301:	learn: 0.0023826	total: 1.65s	remaining: 1.08s
302:	learn: 0.0023798	total: 1.65s	remaining: 1.07s
303:	learn: 0.0023753	total: 1.66s	remaining: 1.07s
304:	learn: 0.0023733	total: 1.66s	remaining: 1.06s
305:	learn: 0.0023720	total: 1.67s	remaining: 1.06s
306:	learn: 0.0023696	total: 1.67s	remaining: 1.05s
307:	learn: 0.0023665	total: 1.68s	remaining: 1.04s
308:	learn: 0.0023650	total: 1.68s	remaining: 1.04s
309:	learn: 0.0023635	total: 1.68s	remaining: 1.03s
310:	learn: 0.0023605	total: 1.69s	remaining: 1.03s
311:	learn: 0.0023595	total: 1.69s	remaining: 1.02s
312:	learn: 0.0023567	total: 1.7s	remaining: 1.01s
313:	learn: 0.0023545	total: 1.7s	remaining: 1.01s
314:	learn: 0.0023518	total: 1.71s	remaining: 1s
315:	learn: 0.0023506	total: 1.71s	remaining: 997ms
316:	learn: 0.0023481	total: 1.72s	remaining: 991ms
317:	learn: 0.0023442	total: 1.72s	remaining: 985ms
318:	learn: 0.0023414	total: 1.73s	remaining: 980ms
319:	learn: 0.0023407	total: 1.73s	remaining: 974ms
320:	learn: 0.0023386	total: 1.74s	remaining: 968ms
321:	learn: 0.0023358	total: 1.74s	remaining: 962ms
322:	learn: 0.0023343	total: 1.74s	remaining: 956ms
323:	learn: 0.0023324	total: 1.75s	remaining: 950ms
324:	learn: 0.0023311	total: 1.75s	remaining: 945ms
325:	learn: 0.0023285	total: 1.76s	remaining: 939ms
326:	learn: 0.0023272	total: 1.76s	remaining: 934ms
327:	learn: 0.0023262	total: 1.77s	remaining: 927ms
328:	learn: 0.0023231	total: 1.77s	remaining: 922ms
329:	learn: 0.0023221	total: 1.78s	remaining: 916ms
330:	learn: 0.0023202	total: 1.78s	remaining: 910ms
331:	learn: 0.0023178	total: 1.79s	remaining: 905ms
332:	learn: 0.0023162	total: 1.79s	remaining: 899ms
333:	learn: 0.0023152	total: 1.8s	remaining: 893ms
334:	learn: 0.0023136	total: 1.8s	remaining: 887ms
335:	learn: 0.0023127	total: 1.81s	remaining: 882ms
336:	learn: 0.0023114	total: 1.81s	remaining: 876ms
337:	learn: 0.0023106	total: 1.81s	remaining: 870ms
338:	learn: 0.0023092	total: 1.82s	remaining: 864ms
339:	learn: 0.0023084	total: 1.82s	remaining: 858ms
340:	learn: 0.0023057	total: 1.83s	remaining: 853ms
341:	learn: 0.0023039	total: 1.83s	remaining: 847ms
342:	learn: 0.0023032	total: 1.84s	remaining: 841ms
343:	learn: 0.0023014	total: 1.84s	remaining: 836ms
344:	learn: 0.0023001	total: 1.85s	remaining: 830ms
345:	learn: 0.0022994	total: 1.85s	remaining: 824ms
346:	learn: 0.0022973	total: 1.86s	remaining: 819ms
347:	learn: 0.0022966	total: 1.86s	remaining: 813ms
348:	learn: 0.0022944	total: 1.87s	remaining: 808ms
349:	learn: 0.0022932	total: 1.87s	remaining: 802ms
350:	learn: 0.0022907	total: 1.88s	remaining: 796ms
351:	learn: 0.0022887	total: 1.88s	remaining: 790ms
352:	learn: 0.0022867	total: 1.88s	remaining: 784ms
353:	learn: 0.0022855	total: 1.89s	remaining: 778ms
354:	learn: 0.0022843	total: 1.89s	remaining: 773ms
355:	learn: 0.0022823	total: 1.9s	remaining: 767ms
356:	learn: 0.0022798	total: 1.9s	remaining: 761ms
357:	learn: 0.0022779	total: 1.9s	remaining: 755ms
358:	learn: 0.0022743	total: 1.91s	remaining: 749ms
359:	learn: 0.0022724	total: 1.91s	remaining: 744ms
360:	learn: 0.0022717	total: 1.92s	remaining: 738ms
361:	learn: 0.0022707	total: 1.92s	remaining: 732ms
362:	learn: 0.0022686	total: 1.93s	remaining: 727ms
363:	learn: 0.0022672	total: 1.93s	remaining: 721ms
364:	learn: 0.0022655	total: 1.93s	remaining: 715ms
365:	learn: 0.0022625	total: 1.94s	remaining: 709ms
366:	learn: 0.0022615	total: 1.94s	remaining: 703ms
367:	learn: 0.0022581	total: 1.95s	remaining: 698ms
368:	learn: 0.0022573	total: 1.95s	remaining: 693ms
369:	learn: 0.0022565	total: 1.96s	remaining: 687ms
370:	learn: 0.0022542	total: 1.96s	remaining: 681ms
371:	learn: 0.0022524	total: 1.97s	remaining: 676ms
372:	learn: 0.0022518	total: 1.97s	remaining: 671ms
373:	learn: 0.0022487	total: 1.98s	remaining: 665ms
374:	learn: 0.0022481	total: 1.98s	remaining: 660ms
375:	learn: 0.0022458	total: 1.99s	remaining: 655ms
376:	learn: 0.0022445	total: 1.99s	remaining: 649ms
377:	learn: 0.0022432	total: 2s	remaining: 644ms
378:	learn: 0.0022418	total: 2s	remaining: 639ms
379:	learn: 0.0022411	total: 2s	remaining: 633ms
380:	learn: 0.0022405	total: 2.01s	remaining: 627ms
381:	learn: 0.0022390	total: 2.01s	remaining: 622ms
382:	learn: 0.0022385	total: 2.02s	remaining: 616ms
383:	learn: 0.0022380	total: 2.02s	remaining: 611ms
384:	learn: 0.0022364	total: 2.02s	remaining: 605ms
385:	learn: 0.0022350	total: 2.03s	remaining: 600ms
386:	learn: 0.0022322	total: 2.04s	remaining: 594ms
387:	learn: 0.0022298	total: 2.04s	remaining: 589ms